### ISSUE TITLE
Select input has different height to text input

### ISSUE THREAD

**Issue by Lukewh** [canonical-web-and-design/vanilla-framework#1901]
## Expected result

For all form elements to have a different height

## Current result

Select is smaller than text input https://codepen.io/Lukewh/pen/VdVMNB

This is on Firefox, btw

**Comment by lyubomir-popov** [comment]
@Lukewh To clarify, the issue here is with white space above inline-block elements, not the height of the elements themselves - screenshot bellow showing what happens when you turn off inline-block.
 There are [various solutions ](https://css-tricks.com/fighting-the-space-between-inline-block-elements/)to this, and I wonder whether these really need to be inline-flex.

![image](https://user-images.githubusercontent.com/2741678/42567599-21a2873e-8502-11e8-8c8a-d8e80c02c951.png)

**Comment by Lukewh** [comment]
I've updated the code on https://codepen.io/Lukewh/pen/VdVMNB to remove all whitespace between elements, but the `select` is still smaller in Firefox:

![screenshot_2018-07-11 vdvmnb](https://user-images.githubusercontent.com/479384/42568208-41829d3a-8504-11e8-99c7-3101b3571979.png)

**Comment by lyubomir-popov** [comment]
@Lukewh ah right, hadn't noticed firefox in the description. Looks like selects don't respect line-height, we need to put height instead and potentially set box-sizing to content box.

**Comment by deadlight** [comment]
I've just checked this in 1.8.1 in FF and it is no longer a problem:
https://codepen.io/deadlight/pen/LwWKdy
