### ISSUE TITLE
“Table mobile card” example doesn’t work

### ISSUE THREAD

**Issue by kwm14** [canonical-web-and-design/vanilla-framework#2163]
_Originally filed by @matthewpaulthomas [here](https://github.com/canonical-websites/vanillaframework.io/issues/201):_

> 1\. Open [the “Table mobile card” page](https://docs.vanillaframework.io/en/patterns/table-mobile-card).
2\. Scroll to the example table.
3\. Resize the window to be very narrow.

> What happens: Apart from its width, the table appearance does not change.
![vanilla-table-mobile-card](https://user-images.githubusercontent.com/19801137/53000854-91724780-3429-11e9-9eb3-6775733ab159.png)

> What should happen: either
> - the page should not be present at all, if the pattern no longer exists; or
> - the table changes appearance to “a new responsive card” as described.

**Comment by lyubomir-popov** [comment]
The problem here is that the switch to the mobile view (what's visible in the screenshot above)happens at a media query that is larger than the docs' embedded iframe width. Given the docs layout, the only way to see the switch would be to open the example in a new tab. I suggest simply adding a link to that.  Would that work for you @matthewpaulthomas?

**Comment by matthewpaulthomas** [comment]
@lyubomir-popov That would be one ingredient for a fix. However, even when I open that example in its own window, I don’t get a “card view” at any width. What I do get is different column headers for the same data.

![image](https://user-images.githubusercontent.com/19801137/68693342-06188380-056f-11ea-850e-169b450a967f.png)

![image](https://user-images.githubusercontent.com/19801137/68693370-16c8f980-056f-11ea-85f9-412c45e41e19.png)

So I guess the example needs revising too.

Separately, since reporting this, I’ve realised that there are several other patterns — for example, [Grid](https://docs.vanillaframework.io/patterns/grid/), [Navigation](https://docs.vanillaframework.io/patterns/navigation/), and [Floats](https://docs.vanillaframework.io/utilities/floats/) — where, on my screen at least, the narrow container prevents me seeing the intended default, making the pattern hard to understand. It might be worth considering navigation that consumes less width on every page (like a mega-menu for the pattern list, and tables of contents that aren’t sidebars either), or else some way of “zooming out” examples by default.
