### ISSUE TITLE
Make line-height unitless

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/vanilla-framework#2195]
## Pattern to amend
Line-height usage in base typography.

## Visual
Before:
![screenshot_2019-03-07 key considerations when choosing a robot s operating system ubuntu 1](https://user-images.githubusercontent.com/1413534/53946266-51fb5a80-40bb-11e9-9e64-f290faca7b27.png)

After (applying `1.5`):
![screenshot_2019-03-07 key considerations when choosing a robot s operating system ubuntu](https://user-images.githubusercontent.com/1413534/53946294-5d4e8600-40bb-11e9-9f64-ca698888fd63.png)

## Context
In base typography we are using `1.5rem` as the line-height value but this takes the font-size from the html element and if we bump the font-size up we do that on the body. Therefore, line-height does not scale with the font-size.

**Comment by lyubomir-popov** [comment]
@anthonydillon unfortunately unitless line-heights are not compatible with vertical rhythm. Due to browser rounding, after about 10 lines the line-height starts to stray from the baseline grid.

**Comment by lyubomir-popov** [comment]
@anthonydillon why the need to bump font-size, and why on the body?

**Comment by kwm14** [comment]
## WG
- Offline convo between @lyubomir-popov and @anthonydillon

**Comment by lyubomir-popov** [comment]
@anthonydillon the issue here was the strange way in which unitless line-heights are rounded:
You can't adjust it to be an exact number of rems, it just rounds down if < .3, rounds to .5 if less than .66, and rounds to the next closest number if above .66: this gif shows the issue:

http://www.giphy.com/gifs/2js6jD3OB4S2LlNnUw

Which means that, unless the line-height you need is exactly 1.5, it is rounded and the errror is quite noticeable:

![image](https://user-images.githubusercontent.com/2741678/54543768-28351400-4996-11e9-8d7a-d2c154e3d779.png)

**Comment by lyubomir-popov** [comment]
Can we close this?

**Comment by lyubomir-popov** [comment]
PR to demonstrate:
https://github.com/vanilla-framework/vanilla-framework/pull/2222

**Comment by deadlight** [comment]
Thanks for explaining this @lyubomir-popov. We won't be switching to unitless line heights but there are other ways to achieve the desired effects.
