### ISSUE TITLE
p-card pattern is not blocked

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/vanilla-framework#2288]
The p-card pattern elements are not scoped by the block. This leads to people using `p-card__thumbnail` in other patterns to hack a solution. All patterns should be scoped to the block element.

Therefore, p-card should be coded like:
```scss
.p-card {
    .p-card__thumbnail {
        ...
    }
}
```

**Comment by deadlight** [comment]
I don't think that we should make all selectors more complex to avoid this, it'll lead to messy CSS and make overrides too specific.

BEM class names are already namespaced so this seems redundant.

This hack is clearly the wrong, of course, but using a "E" without a "B" should just be a code review fail rather than a codebase change.

**Comment by deadlight** [comment]
I'm going to close this issue based on the above.
