### ISSUE TITLE
Spacing between paragraphs in rows in `p-card`

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/vanilla-framework#2447]
When paragraphs of text are placed in grid rows inside of `p-card` pattern there is no spacing between last paragraph and next row.

**To Reproduce**
Have text in paragraphs inside of grid rows in the `p-card` pattern, see: https://jsfiddle.net/bartaz/8zcbj56k/

**Expected behavior**
There should be enough space between paragraphs and headings regardless of usage inside or outside of `p-card` pattern.

**Screenshots**
<img width="856" alt="Screenshot 2019-08-06 at 09 58 23" src="https://user-images.githubusercontent.com/83575/62522057-2c70a980-b831-11e9-8377-de21df863d26.png">

**Comment by deadlight** [comment]
I have looked into this and the issue is caused by a greedy selector in the p-card pattern that targets the first and last elements in the card _and_ any nested containers. I'll change this to only target direct descendants.

Note: the text spacing isn't perfect in either example - the gap between the heading and the paragraph above is still too small. We're investigating solutions to this but you leave it for now if you're happy and the spacing tweaks will come downstream to you in time.
