### ISSUE TITLE
Support p-code-copyable for textareas

### ISSUE THREAD

**Issue by Lukewh** [canonical-web-and-design/vanilla-framework#2453]
## Pattern to amend

p-code-copyable

## Visual

https://codepen.io/Lukewh/pen/YmeyLB

## Context

In snapcraft.io we have multiline copy boxes and to follow the pattern of the code-copyable we've implemented it with a textarea (rather then a code block).
We also have some code that's copyable that isn't CLI focused (so shouldn't have the "$")... the code I've pasted includes this, but there's a [separate proposal for that](https://github.com/canonical-web-and-design/vanilla-framework/issues/2454).

**Comment by deadlight** [comment]
Looks good to me.

@kwm14 is this [example](https://codepen.io/Lukewh/pen/YmeyLB) good, design-wise?

**Comment by kwm14** [comment]
@deadlight makes sense and a good addition to a current component 👍

**Comment by bartaz** [comment]
Should it be `not-cli` or `is-something` (to follow other components)? Or maybe just a BEM `--modifier`?

**Comment by Lukewh** [comment]
> Should it be `not-cli` or `is-something` (to follow other components)? Or maybe just a BEM `--modifier`?

@bartaz This is for the textarea version, not the "not-cli" see [here](https://github.com/canonical-web-and-design/vanilla-framework/issues/2454) for that

**Comment by anthonydillon** [comment]
> Should it be `not-cli` or `is-something` (to follow other components)? Or maybe just a BEM `--modifier`?

Some details here: https://canonical-web-and-design.github.io/practices/coding/stylesheets.html

**Comment by lyubomir-popov** [comment]
@Lukewh @bartaz This seems quite closeto something we already have:
![image](https://user-images.githubusercontent.com/2741678/63939499-551a4680-ca5f-11e9-8f7b-6ad771e5f138.png)

You mention you opted for textarea instead of the existing code block, why? In what cases is the textarea solving a problem the code block isn't suitable for?

**Comment by lyubomir-popov** [comment]
Actually, the screenshot above seems shows a local component of the vanilla docs. Still, the question remains - which version is better and why - an editable textarea, or a non-editable code block. Or maybe both?

**Comment by bartaz** [comment]
@lyubomir-popov I think textarea was chosen because of simplicity of `copy` implementation. We are using ClipboardJS and it supports input fields and textareas directly. It's much easier to select and copy contents of textarea than any regular element in the document.

It seems that Vanilla docs work around that by actually having a script that cleans up content of copied element and puts it into a hidden textarea to copy it. So it requires quite complicated and specific implementation to support copying from something that is not textarea.

Of course textarea has it limitations. We have much less control over styling inside it, code cannot be highlighted in any way etc.

I guess ideally it would be great to have support for all cases:
- non-editable textarea (for minimal styling, easy selecting text and copy)
- editable textarea (minimal styling, easy selecting, editable as form element)
- non-editable pattern (for more complex styling including highlighting code)

**Comment by lyubomir-popov** [comment]
Thanks @bartaz makes sense. Can we move this out of this epic though? It is not an upgrade issue, more a proposal for enhancement.

**Comment by lyubomir-popov** [comment]
@clagom what do we do with this in light of the request to remove the border and copy button?

**Comment by clagom** [comment]
@lyubomir-popov 
I think ideally for now we would need to consider flexible options, e.g.: one just plain text without icons and border; one with just border and no icon; one with icons and border. I think a subtle background could be better than the border, for the discussions we had around this element. 
With these options I think we can iterate and propose solutions to discuss.

**Comment by wgx** [comment]
Copy function is being removed from code snippet.
