### ISSUE TITLE
The return of a side navigation

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/vanilla-framework#2466]
## Visual
![Screenshot_2019-08-09 Zeplin - Project](https://user-images.githubusercontent.com/1413534/62765597-58399c80-ba88-11e9-8915-99edbd519f15.png)

![Screenshot_2019-08-09 Metal as a Service MAAS](https://user-images.githubusercontent.com/1413534/62765642-6e475d00-ba88-11e9-9d23-3e58912a01be.png)

## Context
We are using a side navigation within most applications and documentation since the removal of the aside pattern. I think it would be worth re-implementing one with features such as:
- Navigation nesting
- Numerical indicator
- Selected navigation item
- Hover

## State
This depends on the feature set. But I think we will need at least selected and not selected.

**Comment by bartaz** [comment]
Some examples from snapcraft:

<img width="285" alt="Screenshot 2019-08-09 at 10 50 10" src="https://user-images.githubusercontent.com/83575/62766780-8670a980-ba93-11e9-9f18-f507b3e75cd3.png">
<img width="287" alt="Screenshot 2019-08-09 at 10 50 02" src="https://user-images.githubusercontent.com/83575/62766781-8670a980-ba93-11e9-8bc9-11debe4fcfba.png">

**Comment by spencerbygraves** [comment]
We will need to do some design work on this to make sure we have a solution that works/scales for all products.

**Comment by kwm14** [comment]
Happy to bring back the sidebar navigation but in a newly reformed style 😉 

The reason we deprecated it in 2.0 was due to it not being used and was the largest component in the framework, it also depended on other components:

- Our **Accordion** component which serves the same purpose
- Our **Search** component which most sites don't include in the sidebar navigation
- Our **External links** component

So it was a big complex component. Happy to go with the proposal as it's now being used in our applications and new dashboards 👍

**Comment by kwm14** [comment]
## WG
- Agreed to rework the sidebar navigation to cater for new application needs
  - Secondary and tertiary levels
  - Number indicators
  - Icons
  - Open and collapse 
- Bring this up as a work item/discussion in Paris 👍

**Comment by bartaz** [comment]
We are working on side nav
