### ISSUE TITLE
Inline list item margin makes buttons too far apart

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/vanilla-framework#2525]
In Vanilla, [_patterns_lists.scss contains](https://github.com/canonical-web-and-design/vanilla-framework/blob/1819abbef989e3f932b0a02d3a8e0bb45c02c789/scss/_patterns_lists.scss#L31):
```scss
// Mixin for inline list items
@mixin vf-inline-list-item {
  display: inline;
  list-style: none;
  margin-right: 1.25rem;
```

On [dqlite.io](https://dqlite.io/), this causes two buttons…
```html
<ul class="p-inline-list">
  <li class="p-inline-list__item"><a href="/docs" class="p-button--positive u-no-margin--bottom-small">Docs</a></li>
  <li class="p-inline-list__item"><a href="https://github.com/canonical/dqlite/releases" class="p-button--neutral u-no-margin--bottom-small">Download</a></li>
</ul>
```
…to appear 1.25rem + 1 character space apart:

![image](https://user-images.githubusercontent.com/19801137/64098011-a0816d00-cd5d-11e9-88e0-40ac9e041734.png)

But according to the examples on [the Buttons reference](https://docs.vanillaframework.io/patterns/buttons/), buttons should be only 1rem apart:

![image](https://user-images.githubusercontent.com/19801137/64098108-efc79d80-cd5d-11e9-9f45-a96aa2cc45f2.png)

So it looks as though:
- dqlite.io is using the wrong markup, in a way that would affect the button spacing, or
- all inline list items should be 1rem apart, not 1.25rem, or
- there should be extra CSS for changing list item spacing when those items happen to be buttons.

**Comment by lyubomir-popov** [comment]
Well spotted @matthewpaulthomas! The 1.25rem turns out to be a hardcoded value from 2 years ago, which I've now replaced with the correct variable for this situation, $sph-outer.

You are also right that these shouldn't be in an inline list. I don't see why no margin utilities are used either. The markup could be simplified to:
![image](https://user-images.githubusercontent.com/2741678/64104332-f65d1180-cd6b-11e9-9860-6f59ea6568df.png)
