### ISSUE TITLE
The stepped-list needs some padding at the top

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/vanilla-framework#2534]
The stepped-list has bullets pulled up which reduces the padding between the element before. I think stepped-list should have padding-top applied to compensate.
https://codepen.io/anthonydillon/pen/qBWpJML

**Comment by bartaz** [comment]
It's a bug: ![Screenshot 2021-03-15 at 12.10.44.png](https://images.zenhubusercontent.com/593a660851aa2c30578102bb/fdda0f84-9b18-484d-8fa3-540a66e6a014)

**Comment by sowasred2012** [comment]
Discussed with @lyubomir-popov, and decided against adding top padding to the list so as not to try to make it account for content that may or may not be above it. The bug was fixed in 2.4.0, when negative margins were removed from headings:
![Screenshot from 2021-04-28 14-51-44.png](https://images.zenhubusercontent.com/5cd93aaf2406d87914830598/94c55faf-e8e8-49f3-8da5-d220a8d9bbee)
