### ISSUE TITLE
Baseline / vertical rhythm question

### ISSUE THREAD

**Issue by cekvenich** [canonical-web-and-design/vanilla-framework#2543]
(I plan on using this in a project).
Q: I look at your wonderful examples, eg:
- https://docs.vanillaframework.io/examples/templates/maas-layout/
and it includes baseline :-) 👍 

But it does not look aligned. Can I get some help understanding this please?

**Comment by lyubomir-popov** [comment]
Hi @cekvenich, can you provide some additional details:

- a screenshot with the baseline grid on
- Browser version, OS

This is what it should look like:
![image](https://user-images.githubusercontent.com/2741678/64940560-29b79a00-d85c-11e9-8f62-76f8400e1354.png)

**Comment by lyubomir-popov** [comment]
I think I spotted what's wrong - navigation and tabstrip did not have explicitly set line-height, and inherited from the html element. At resolutions over 1680, where we change font-size and line-height on the html element, these two components no longer align to the grid. 

A fix is coming in https://github.com/canonical-web-and-design/vanilla-framework/pull/2544
![image](https://user-images.githubusercontent.com/2741678/64947427-401e1f80-d875-11e9-8d13-b511357d7987.png)

**Comment by cekvenich** [comment]
Awesome. I think vertical rhythm  is a key part.  (aside, I'll post an example soon and touch on  custom element)

**Comment by lyubomir-popov** [comment]
@cekvenich one thing to note - if you decide to use a different font in place of the default (ubuntu), you may need to adjust the [$nudges sass map](https://github.com/canonical-web-and-design/vanilla-framework/blob/2f6d44b6aa391afbff5b887cf7e60493ed456059/scss/_settings_spacing.scss#L40). 

This is because the padding-top applied to text to "nudge" it to the closest baseline depends on two things:

- the font itself - where the characters appear within the line height
- the line-height of the text element. Any change to that as for example on a media query, would also require adjustment of the nudges used.

**Comment by cekvenich** [comment]
Thank you! I plan to use Open Sans:300 mostly, but others as well. I think others use .js to align. I plan to learn to use map-get(), so it is aligned. Likely I'll need help when I get to that part.
