### ISSUE TITLE
Document the usage of the code-copyable pattern

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/vanilla-framework#2568]
## Pattern to amend
p-code-copyable

## Context
It has been suggested a number of times that we over/incorrectly use the code-copyable pattern in places. We should document when and when you shouldn't use the pattern. Limiting this patterns use to these cases only.

**Comment by matthewpaulthomas** [comment]
Part of the issue is that the current implementation is noisy:
- it has a border, which makes it look like a text field when it isn’t
- it has a prompt (`$`), which is useful mainly for distinguishing input vs. output in a multi-line field, but this is a single-line field
- the button is grey and has its own border
- the icon is too detailed (with a blurry arrow) to understand at a glance.

In comparison, for example, the Copy button in Google Calendar:
- has no border
- appears only when you hover over the element
- has a background only when hoving over the button itself
- has a very simple icon.

**Comment by fitojb** [comment]
Personally, I think that making controls appear on hover/focus is detrimental for accessibility.

**Comment by matthewpaulthomas** [comment]
Sure. Vanilla’s and Google’s are pretty much opposite extremes, with plenty of possibilities between.

**Comment by matthewpaulthomas** [comment]
> Vanilla’s and Google’s are pretty much opposite extremes

This probably belongs in the “collect examples” stage of a future redesign task — but in the interests of fairness, I just encountered one blockier than Vanilla’s, [on IBM X-Force](https://exchange.xforce.ibmcloud.com/vulnerabilities/169598).

![image](https://user-images.githubusercontent.com/19801137/67279269-901a8280-f4c2-11e9-9413-4f843a09f0ca.png)

IBM’s own Carbon Design System has [a more sedate version](https://www.carbondesignsystem.com/components/code-snippet/code).
