### ISSUE TITLE
Font-display using optional

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#2569]
One of Harry Roberts' more design related recommendations: using font-display so visitors see a font as quickly as possible.

We need a decision as to which flavour of font-display we prefer:

swap - meaning as soon as the ubuntu font loads, it swaps the default system font
optional - meaning the swap only happens when (if) the visitor navigates to another page

@deadlight @kwm14  Just wanted to file this so it is tracked somewhere.

**Comment by anthonydillon** [comment]
This is not 100% true.

**Swap** means use system font until the Ubuntu font loads and swap it (at any time after load)

**Optional** means use the system font until the Ubuntu font loads. The difference is that if the font takes longer then the browsers threshold (3 sec) to load then it never swaps the font.

In my option, **optional** is best as after 3 seconds the user is already reading the text and it would be distributive to swap fonts as they read.

All further pages will have the font cached and therefore load with the page.

**Comment by lyubomir-popov** [comment]
Oh I see thanks for the clarification @anthonydillon

**Comment by spencerbygraves** [comment]
It seems either solution would be an improvement. As @bartaz's [demo shows](https://github.com/canonical-web-and-design/snapcraft.io/issues/2289), we should choose a fall back font that is close to Ubuntu.

**Comment by clagom** [comment]
Ideally the swap would let users to see the design how originally intended (with Ubuntu font and typography balance), even if I agree that feels always a bit weird when you actually see the font change. But the alternative is that the Ubuntu font is not displayed at all.
Can we test the swap with a font that is close to Ubuntu as @spencerbygraves said?
Still, this is only about the first time visit, as the other times the font will be cached anyway.

**Comment by matthewpaulthomas** [comment]
> In my option, optional is best as after 3 seconds the user is already reading the text and it would be distributive to swap fonts as they read.

We could test this, if we assume that changing the font of body text is disruptive, while changing the font of headlines is not. Take a sample of pages from our sites, importance weighted by how often people visit each one as the first page in their session. (Visiting it as a later page doesn’t count, because the font will be cached by then.) The importance values should add up to 1.

Then for each page, record the average time the first piece of body text (for example, a `<p>` or `<td>`) is scrolled into view, and record when the font becomes available. If the body text scrolls into view earlier, Flash Of Unstyled Body = how much earlier. If the font becomes available earlier, FOUB = 0. Then multiply each FOUB by the importance of that page. The end total would be the average time that body text appears in the wrong font in a user session. If it’s more than, say, two seconds, we could say that’s too long and use `optional`; if it’s less than that, we could say that’s fine and use `auto` or `swap`.

That might seem a lot of work, but this seems like the kind of issue where you’d need to put in a lot of work to be able to make a better decision than the browser can by itself.

**Comment by kwm14** [comment]
## WG Notes
**Phase 1**
- Update the fallback font stack
- Test the subsetting
  - Speed
  - Record [tests](https://github.com/canonical-web-and-design/snapcraft.io/issues/2289#issue-502430595) similar to @bartaz 
  - Test tool for recording - https://www.webpagetest.org/

**Phase 2**
- See if the choice is optimized and reliable from Phase 1 investigation

**Comment by bartaz** [comment]
@bartaz plan for next iteration

**Comment by barrymcgee** [comment]
@bartaz Has this slipped from your roadmap? Any idea when it might be tackled?

**Comment by bartaz** [comment]
@barrymcgee I think it did slip. 

And TBH I have no idea what the status is and what next steps for it were decided.

Did we settle on using swap or optional? @spencerbygraves @lyubomir-popov?
Should be bring it up to WG just to discuss and review next steps?

**Comment by spencerbygraves** [comment]
@bartaz looks like next steps were agreed back in October :point_up:

**Comment by bartaz** [comment]
@spencerbygraves I've seen the WG notes from October, but they barely mean anything to me at this point.

"Update font stack" - update to what? Do we have any proposed alternative to fallback font?

"Test the subsetting" - what 'subsetting' we wanted to test? If it was about using subset of characters to make the font smaller we already support that in Vanilla with `$font-use-subset-latin`.

**Comment by spencerbygraves** [comment]
@bartaz ok, sounds like we need to discuss it again 👍

**Comment by bartaz** [comment]
WG notes:

- We prefer 'optional' as a value.
- Pick fallback fonts - @lyubomir-popov @spencerbygraves to review the options with brand - take wrapping into account

Next steps:
- use 'optional'
- improve font stack
