### ISSUE TITLE
Address the use of max-width on text elements in the documentation

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#2586]
Text line length in vanilla is limited using max-width. The reasons behind this choice are not addressed in the documentation, so there's nowhere to point to when someone proposes removing it. It would be nice to have a summary of the reasons why text shouldn't span the full width of its container, with references to research etc.

**Comment by matthewpaulthomas** [comment]
When I investigated line length a few years ago, I was surprised not to find any multivariate research. Lots of tradition (“…widely regarded as…”, “…considered to be…”) and appeals to authority (“Bringhurst says…”). And a fair bit of univariate research, that is, varying line length only, for a particular number of words, in one particular typeface, at one particular size, with one particular line spacing, at one particular screen resolution, with vertical scrolling either not required or not even mentioned. But no investigation of how each of those other six factors affect the result. And then there’s the problem that optimising for speed, comprehension, or enjoyment produces wildly different results.

Maybe that’s changed since. Even without applicable research, though, it would be great to have a clear explanation something like:
- Vanilla sets a max-width of _X_ for everything except headings, which are brief, so we allow them to be a bit wider _Y_
- (In case you’re wondering, we make an exception for these docs themselves for [a technical reason](https://github.com/canonical-web-and-design/vanilla-framework/blob/master/docs/sass/_settings.scss#L7))
- It’s reasonable to make an exception in these limited cases:
  - If it will avoid an orphan in some fixed, high-profile text, like a promotional banner
  - If the width of your box is a _little_ more than _X_, so sticking to _X_ would make the box look unbalanced
  - … (Any others?)

Defining appropriate exceptions might help discourage people from making exceptions in other cases.

**Comment by lyubomir-popov** [comment]
True, there's no definitive answer to what the optimum number of characters per line (cpl) is, and any of the studies can be challenged by saying they didn't account for additional factors. But regardless of the varying recommendations, there's a couple of things that all research shares:

1. All studies test with an upper limit (55/60/75/80/95cpl), that rarely exceeds 2x the lower limit (45cpl). The median is roughly the traditional value of 75cpl. That to me indicates that there's a cutoff point after which researchers find it pointless to test. 

For comparison, letting a line of text stretch end to end on a 1600px screen is over 2 times more than the highest value I've seen in research (95cpl).

2. Speed of reading and comprehension do not stay constant when cpl changes. By itself, this means that it should be something that is "designed", rather than left to window width. 

Lacking consensus on what the optimum is, any choice we make will be opinionated. Still, an informed choice (based on experience, the lengths used in the studies, those recommended by authorities like Bringhurst, tradition etc., all of which also accustom readers to certain widths), would be better than leaving things to chance, or arbitrary considerations like the width of an adjacent element.

Of course all of this should be laid out in the documentation and I will make sure it includes the points you've mentioned above.
