### ISSUE TITLE
SSO - merge login templates

### ISSUE THREAD

**Issue by deadlight** [canonical-web-and-design/vanilla-framework#2631]

**Comment by deadlight** [comment]
https://code.launchpad.net/~deadlight/canonical-identity-provider/merge-2-registration/+merge/375393

**Comment by kwm14** [comment]
A big chunk of the diff is just reformatting code, afaict. A consistent, pretty formatting is always great! But I wonder if this can be split into two branches: one for reformatting only, and another with actual code changes.

**Comment by kwm14** [comment]
_**Daniel**_
Let's get in touch next week, I would suggest:

- Apply the fixes Maxi suggested
- Run the test suite locally (ARGS="-c $YOUR_CORES" will make it faster)
- Let us know if you see any other failures, we can help fix them.

I can also help by running things locally and fixing broken tests, though I'm a bit limited at the moment because of sprint.

Also, as for Maxi's first request - if it's easy/doable to separate the reformatting from the actual changes (can be the same MP, just in different commits) that would ease review. If it's difficult to do we can leave it as-is.
