### ISSUE TITLE
What does an empty table state look like? [Legacy issue for research]

### ISSUE THREAD

**Issue by barrymcgee** [canonical-web-and-design/vanilla-framework#2663]
When building apps, it's sometimes required to display an empty table - either to convey to the user that a certain dataset does not exist or that it does exist but is not yet available.

What does this look like?

In the interim, I've made a proposal to Vanilla React Components library to use the `<caption>` element to display an empty state message:

<img width="887" alt="Screenshot 2019-11-21 at 11 19 29" src="https://user-images.githubusercontent.com/505570/69333609-e4935800-0c50-11ea-8f13-e31abd6c3fea.png">

This ensures the table is still semantically valid.

**Comment by matthewpaulthomas** [comment]
This looks similar to the first of [the empty-state design options for snapcraft.io](https://drive.google.com/open?id=1GagV2ivr6NJ1vVDhB--2bSnGkF0s8nx_).

If you added more vertical margin to the empty-state text (making the whole table taller), it would look less like it’s associated with “Foundation Cloud” in particular. And using more table-specific text would encourage developers to be more specific themselves, rather than just copying and pasting “No data to display”.

Design guidelines should warn developers never to mislead people by using empty-state text for a table that just hasn‘t loaded yet. Loading state should be [a different thing](https://kyusuf.com/post/fake-it-til-you-make-it-css/).

**Comment by anthonydillon** [comment]
Absolutely, we should design for all possible situations:
- Loading
- Error loading
- Loaded:
  - Empty
  - Few
  - Lots

I believe @lilyvidenova is spending some time this cycle to initiate the table guidelines. I have added these states to the [table guideline document](https://docs.google.com/document/d/1OuLk1V_hYCd-9-DK2rROaSPOrmViARFWPezxfJQ2gVk/edit#heading=h.396bd3fk3q8g) to be fleshed out.

**Comment by bartaz** [comment]
We should design the table states and implement necessary styles.

**Comment by anthonydillon** [comment]
This should be documented in the UX Vanilla documentation of the table pattern.

**Comment by clagom** [comment]
To be considered for the work on the epic #952
