### ISSUE TITLE
Remove the toggle and toggle JS from examples

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/vanilla-framework#2668]
Now that the red lines are always on in examples can we please remove the toggle and the extra JS from the example template please.

**Comment by lyubomir-popov** [comment]
The lines are _under_ the white component background, their purpose is to tip you off when a component or template, as a whole, has drifted from the grid.

But to inspect exactly what is off, you still need the "foreground" grid that is switched on by the toggle:

Background grid:

![Uploading Screenshot 2019-11-26 at 15.02.41.png…]()


Foreground grid:

<img width="814" alt="Screenshot 2019-11-26 at 15 02 17" src="https://user-images.githubusercontent.com/2741678/69645327-ea78a700-105d-11ea-89df-760cdb0670cd.png">

**Comment by bartaz** [comment]
As pointed out separately in #2699 the grid gets visible in the docs sometimes and it looks weird and confusing.

If it's needed to debug components both foreground and background lines should be enabled/disabled together with a switch.

**Comment by lyubomir-popov** [comment]
With codepen this is no longer an issue. @anthonydillon can we close this?

**Comment by anthonydillon** [comment]
The issue now is that it doesn't work. Could we fix that first?

**Comment by bartaz** [comment]
> The issue now is that it doesn't work. Could we fix that first?

@anthonydillon What doesn't work? The [toggle in the examples](https://vanillaframework.io/docs/examples/patterns/accordion/default) is working as before:

![toggle](https://user-images.githubusercontent.com/83575/96116920-8b2bbb80-0ee9-11eb-97ed-a2ba6328c021.gif)

It seems the original issue reported here is about the baseline background being visible in docs pages in embedded examples, which is not the case since CodePen.

**Comment by anthonydillon** [comment]
Oh sorry, I mistook the toggle functionality. I thought it was meant to remove the red lines outside the pattern also.

Yes close please.
