### ISSUE TITLE
Add datalist component

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#2673]
Vanilla lacks styling for a [datalist ](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist). 

We probably need some design here - @matthewpaulthomas recently mentioned it is closer to a button than a select for example.

**Comment by matthewpaulthomas** [comment]
Sorry I was unclear. In #2665 I meant to say that a radio menu (`<select>`) should look more similar to a menubutton than to a text field, since it’s closer in behaviour. I mentioned `<datalist>` because in native toolkits (though not yet in browsers by default), it behaves as a combination of a menubutton and a text field, so ideally it looks like a combination of both. It’s a continuum of appearance reflecting behaviour:

![Text field, combo box, menubutton, button, radio menu(3)](https://user-images.githubusercontent.com/19801137/70225950-e3c9ee00-1747-11ea-93c8-75f4d20bd853.png)

**Comment by spencerbygraves** [comment]
WG: approved to investigate how it would display in Vanilla currently, then go from there.

**Comment by yj2303** [comment]
I would like to work on this issue. Kindly assign it to me.

**Comment by bartaz** [comment]
@yi2303 Thanks for the interest in the issue. This task is planned for when RGSoC starts in July. It's not ready to be assigned to and worked on.

**Comment by bartaz** [comment]
We want to make sure we can control the style of chevron.
