### ISSUE TITLE
Build new homepage template

### ISSUE THREAD

**Issue by kwm14** [canonical-web-and-design/vanilla-framework#2902]
## Summary

Build a newly designed homepage

## Details
Design [discussion and exploration](https://github.com/canonical-web-and-design/design-vanillaframework.io/issues/15)
Signed-off [design](https://github.com/canonical-web-and-design/design-vanillaframework.io/issues/15#issuecomment-543196085)

## Visual
_Template (only change will be color gradient once reviewed and signed-off._

![Global-homepage-004](https://user-images.githubusercontent.com/17748020/67488137-31dad480-f667-11e9-9676-51bf7d7faa4c.png)

**Comment by bartaz** [comment]
@lyubomir-popov This is a home page redesign proposed by Karlos. We could revisit it now when updating the site or just close it if it's not relevant anymore.

**Comment by tanisha03** [comment]
@bartaz  what are we expected to do ?

**Comment by bartaz** [comment]
@tanisha03 Hi. Thanks for reaching out. Summer of Code hasn't started yet, so this task is not ready to be worked on.

The vanillaframework.io site will be having a redesign, so this particular issue may not be relevant in July when RGSoC starts. This issue here was to give you an idea of what you may be working on in the summer.

**Comment by bartaz** [comment]
We are not planning redesign at this time.
