### ISSUE TITLE
Align accordion icons top instead of center 

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/vanilla-framework#2926]
## Pattern to amend
Accordion

## Visual
![image](https://user-images.githubusercontent.com/1413534/76531084-95c23600-646c-11ea-865a-1cee3d0ccc15.png)

## Context
During the build of the [OpenStack distro comparison page](https://ubuntu.com/openstack/compare) to was requested that we align the icon of the accordion pattern to the top if the text wraps onto multiple lines.

For example:
![image](https://user-images.githubusercontent.com/1413534/76531355-fe111780-646c-11ea-8c52-eb3c2ce1292d.png)

I think this is a reasonable default.

**Comment by deadlight** [comment]
```
.p-accordion__tab {
  background-position: top $spv-inner--medium left 1rem;
}
```

**Comment by bartaz** [comment]
@lyubomir-popov Are we fine with this proposal (treat it as bug, can it go straight to triaged) or should we discuss it in working group?

**Comment by lyubomir-popov** [comment]
Yes, this is a bug, the icons should be top aligned.

**Comment by bartaz** [comment]
While this sounded as a simple fix, positioning icon from the top is not trivial, because we don't know what is in the accordion button, we don't control the line height or font size.

While we can make 'top' work for standard example, we can easily imagine someone using heading in accordion:

![Screenshot 2020-05-28 at 15.13.02.png](https://images.zenhubusercontent.com/593a660851aa2c30578102bb/e92a6cbd-ccf3-4057-9d1e-c9a34b016fde)

And while `<h2>` may be a bit extreme example, we have cases of non starndard sizes in accordions:

![Screenshot 2020-05-28 at 15.12.06.png](https://images.zenhubusercontent.com/593a660851aa2c30578102bb/15ae09d6-b70e-408b-bbb1-2ff50d67a867)

Setting 'top' for generic text case will break those.

And on CSS level, we don't know, and can't 'check' what font size child elements have. We will not know what is the size of 'one line of text' of whatever is on accordion.

Our closest approximation is positioning the icon in the center (which is currently implemented), but breaks in case of wrapped accordion text.

@lyubomir-popov Any ideas how to tackle this?

**Comment by lyubomir-popov** [comment]
@bartaz I worked out optimal positions of icons compared to any heading size in the [font metrics example ](https://vanillaframework.io/docs/examples/utilities/font-metrics).

Just replace the check icon with a minus:

![image](https://user-images.githubusercontent.com/2741678/83147452-9a9f9900-a0ef-11ea-9daa-ba289c4f670a.png)
