### ISSUE TITLE
Missing figure documentation

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/vanilla-framework#2930]
Vanilla has styling for an image figure (italic) which is not documented in the images pattern.
https://codepen.io/anthonydillon/pen/rNVvEpv

**Comment by akansha006** [comment]
Hi!
I would like to work on this issue. Please assign this to me.

**Comment by matthewpaulthomas** [comment]
@akansha006 Hi, welcome to Vanilla! You’re welcome to submit a PR for this issue (or any other issue), no need to be assigned.

Here’s [the doc that needs updating](https://vanillaframework.io/docs/patterns/images).

If you look at [the source of that doc](https://github.com/canonical-web-and-design/vanilla-framework/blob/master/templates/docs/patterns/images.md), you can see that it links to examples in the examples/ directory. So probably the first thing to do is to [“Create new file” in the examples/ directory](https://github.com/canonical-web-and-design/vanilla-framework/new/master/templates/docs/examples) containing HTML similar to what @anthonydillon provided in the Codepen above.

Then you can update [the doc](https://github.com/canonical-web-and-design/vanilla-framework/blob/master/templates/docs/patterns/images.md) so that it links to the new example, in the same way that it links to the other examples.

**Comment by BellatrixLestrangee** [comment]
Greetings, I was trying out this issue and faced a little confusion. The example links seem to be broken in [source doc](https://github.com/canonical-web-and-design/vanilla-framework/blob/master/templates/docs/patterns/images.md). 
(Do these need updating?)

**Comment by bartaz** [comment]
@BellatrixLestrangee The markdown file you are linking is used to render this documentation page (https://vanillaframework.io/docs/patterns/images) where example links work correctly.

The examples themselves are located in [/templates/docs/examples](https://github.com/canonical-web-and-design/vanilla-framework/tree/master/templates/docs/examples) directory. 

To see the site locally you should follow README instructions to use `./run` script and run the server.

**Comment by BellatrixLestrangee** [comment]
Got it! Thanks for help!
