### ISSUE TITLE
Segmented control / Button group pattern

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#2939]
We currently implement grouping controls differently in JAAS, RBAC and MAAS:

JAAS: a button group, similar to apple's "Segmented control":
![image](https://user-images.githubusercontent.com/2741678/76986279-5f3b5e00-6939-11ea-83ea-b8f220ae6cec.png)

RBAC: individual buttons:
![image](https://user-images.githubusercontent.com/2741678/76986317-6cf0e380-6939-11ea-8587-6eb398e33f97.png)

MAAS: a select:
![image](https://user-images.githubusercontent.com/2741678/76986411-872ac180-6939-11ea-9760-eafb236cdf80.png)

Visually, the JAAS component seems most appealing. Should it become a vanilla pattern so we can recommend it as the default grouping mechanism? A few things to consider:

- Is there enough justification to say existing options are not fit for this purpose? Options could be a series of radio buttons, tabs, individual buttons
- The current design in JAAS uses it for mutually exclusive actions; will it hold up if you have more than one turned on? If you do, would it need a "deactivate all" control?
- could it be a modifier on the regular button, to make it fuse to the left / right / both sides?
- it is one of a few components that come in a smaller vertical height; if we adopt this as the default, we need to provide analogous minimised-height versions of search boxes, inputs etc., so they can sit next to each other and align properly, which currently doesn't happen in jaas

## Visual

Provide a screenshot or link to a prototype of your pattern proposal.

## Context
 When we have a series of related actions

## State

Does this pattern have state? If so, what are the different states (e.g. accordion with closed/open states)?

## Progressive enhancement

A pattern should be designed small screen first. How does this pattern scale up?
How will this pattern degrade on less competent browsers?

**Comment by spencerbygraves** [comment]
>The current design in JAAS uses it for mutually exclusive actions; will it hold up if you have more than one turned on? If you do, would it need a "deactivate all" control?

The button group in Jaas was designed to emphasise that only one could be selected at a time. We also use individual buttons, which can be seen on a model details page.

**Comment by matthewpaulthomas** [comment]
> Options could be a series of radio buttons, tabs, individual buttons

Tabs are typically for viewing different data (e.g. spreadsheet pages, Web pages, MAAS machines vs. pools), not for viewing the same data a different way.

I like the JAAS-style button group (though the borders could be tidier).

> A pattern should be designed small screen first. How does this pattern scale up?
How will this pattern degrade on less competent browsers?

Perhaps the control could be rendered as a `<select>` whenever you’re on a simpler browser, or whenever there isn’t enough room for a button group — whether that’s because there are a lot of options, or because the screen is narrow.

If so, the markup could be simply something like `<select class="is-grouping"><option>None<option>by Status<option>by Owner`…`</select>`

> The current design in JAAS uses it for mutually exclusive actions; will it hold up if you have more than one turned on?

I really liked the _look_ of the control presented on Friday. But I think subgrouping is both complex enough and rare enough, as a feature, that any single control that tried to convey both would be pretty hard to understand. I think they’d need to be presented separately:

Group: [ by Status ___ ↕] Subgroup: [ No __________ ↕]

**Comment by lyubomir-popov** [comment]
Thanks for the input @matthewpaulthomas, I'll try to incorporate it into the design proposed on Friday. If that works then maybe we can use that for one level of grouping.

**Comment by lyubomir-popov** [comment]
We've decided on the following look for the grouping controls, so I guess we can close this until we decide to revisit nested grouping?

![image](https://user-images.githubusercontent.com/2741678/78901940-f4310300-7a70-11ea-881c-a10fde9d0d03.png)
