### ISSUE TITLE
Table expanded panel limited to one expansion per row

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#2958]
## Pattern to amend

The current expanding table pattern assumes a table row can have only one cell that expands into a panel. We have cases where we need:

1) Multiple cells expanding into panels
2) Indication which cell the current panel belongs to
3) Resolution to what happens when the expanded panel repeats part of the information visible in the cell or row before it was expanded, as in the maas example below:

Add pattern name(s) here
![image](https://user-images.githubusercontent.com/2741678/77908579-ae5f8800-7283-11ea-83da-d560817acef6.png)
![image](https://user-images.githubusercontent.com/2741678/77908971-63924000-7284-11ea-96be-5a57f0b9aa02.png)
![image](https://assets.ubuntu.com/v1/1782e4aa-installconfig-networking__2.4_discovery.png)

For consistency, the expand "trigger" should probably match the accordion expand icon, and we have separate conversations about making that a chevron instead of the current + -
 icons.

## Visual

TBD

## Context

See above

**Comment by lyubomir-popov** [comment]
Related proposal for the UA renewels page: 

![image](https://user-images.githubusercontent.com/2741678/77933465-bf6dc080-72a6-11ea-9995-17d26a22bcdb.png)

**Comment by lyubomir-popov** [comment]
Additional existing implementation to consider:

![image](https://user-images.githubusercontent.com/2741678/77935512-694e4c80-72a9-11ea-918d-547130742b75.png)

**Comment by matthewpaulthomas** [comment]
> Resolution to what happens when the expanded panel repeats part of the information visible in the cell or row before it was expanded, as in the maas example below

I see two approaches. One is, as [I suggested for UA](https://github.com/canonical-web-and-design/ubuntu.com/pull/7042#issuecomment-605642595), to move the info from its position in the collapsed view to its position in the expanded view:

•|•
-|-
![imminent-0](https://user-images.githubusercontent.com/19801137/77850965-fd4ae600-71cd-11ea-9960-35b0f04c4f40.png)|![imminent-1](https://user-images.githubusercontent.com/19801137/77850966-fe7c1300-71cd-11ea-9641-497ae5a2fcc5.png)

The other is to lay out the other info, in the expanded view, in such a way that it doesn’t need to repeat the info in the collapsed view. I’d suggest that for MAAS — make expansion actually enlarge the row to reveal _only_ other stuff, rather than opening a differently-coloured panel that shows the same info mixed in with other stuff.

**Comment by bartaz** [comment]
Work is continued in canonical-web-and-design/vanilla-framework#3563
