### ISSUE TITLE
Side navigation highlight colour should be based on accent color

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/vanilla-framework#2966]
The new side navigation component has a highlight border. This border colour should be based on the accent color. Currently it's `$color-sidenav-item-border-highlight`.

This is causing people to write custom styling to use the pattern.

**Comment by lyubomir-popov** [comment]
- Agreed to treat navigation highlight as a semantic colour rather than an accent. 
- Avoiding brand/accent tinting of highlights is an intentional part of the redesign of the side navigation, customising that should be discouraged on product level
- Mention this decision in the documentation for clarity

**Comment by bartaz** [comment]
Next steps:
- update documentation
