### ISSUE TITLE
CodePen examples are very narrow (often showing mobile view)

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/vanilla-framework#2983]
CodePen examples embedded in documentation are quite narrow. This causes issues for large, full width or highly responsive components, because it's requires very large screen to trigger large screen breakpoint in the embedd.

Any screen with resolution smaller than ~1350px wide will show only medium (tablet) styles in CodePen.

![Screenshot 2020-04-16 at 13.51.08.png](https://images.zenhubusercontent.com/593a660851aa2c30578102bb/07858fa9-c968-47b1-a986-c43b995abcb9)

**Comment by anthonydillon** [comment]
Can you init the embed to start at .5x zoom?

**Comment by bartaz** [comment]
I thought about it as well, but I don't think we can: https://blog.codepen.io/documentation/prefill-embeds/

**Comment by matthewpaulthomas** [comment]
If it‘s dependent on however wide `main-content` happens to be, it’s always going to happen on some devices. Two ways to make it happen less often:
- Replace the left sidebar with a mega-menu (as I hinted at in [my sketch for design-vanilla-framework#445](https://github.com/canonical-web-and-design/design-vanilla-framework/issues/445#issuecomment-578179183)):
    ![image](https://user-images.githubusercontent.com/19801137/79542965-872af800-8084-11ea-8371-e5c7d826692d.png)
- When a page has a table of contents, place that below the main heading, rather than in its own sidebar.

But that’s kinda dodging the problem, which is that this is a demo of a pattern that has width-dependent variations. You should be able to see _all_ those variations without resizing your browser window (since, for example, on a tablet you often can’t).

That suggests having some kind of toggle to change the width of the Codepen iframe, even if that sometimes requires horizontal scrolling.

**Comment by bartaz** [comment]
There already is a "toggle" -  "Edit in CodePen" button that opens example full screen. But it's quite hidden in CodePen frame and not directly related to this issue.

We can add similar solution by simply adding a link to a full screen example. This will allow user to see example directly in browser window, so they can interact with that (resize, use dev tools, etc) without having to deal with docs or codepen frames around it.

We have all these pages as examples available, so it's just a matter of linking to them.
And to make it even easier - we even link to these pages exactly from the docs. Only how these links are removed and replaced by CodePen embed. 

So a fairy simple workaround would be to keep the link, render CodePen above it.
And we could reword the link text to be something like "Show full screen example of dark navigation". And maybe some styling can make the link more prominent.

<img width="784" alt="Screenshot 2020-04-17 at 09 57 47" src="https://user-images.githubusercontent.com/83575/79546005-f0653800-8091-11ea-8f97-65e46ab943ef.png">

**Comment by bartaz** [comment]
We removed CodePen, and also with our current layout embedded examples are wider so it is not such a big issue:

![Screenshot 2021-03-05 at 07.49.26.png](https://images.zenhubusercontent.com/593a660851aa2c30578102bb/de4816b1-7f11-461c-8148-05f3ea55920c)
