### ISSUE TITLE
Slight gap between table header and body

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/vanilla-framework#3087]
There is a slight gap between the table head and body due to an empty `::after` on the thead element. I am not sure that its there for but causing a slight gap only on first render but when you resize the browser sorts it out:

https://github.com/canonical-web-and-design/vanilla-framework/blob/e3e4a919a6df82c5b317db3225096047aff4ad5c/scss/_base_tables.scss#L33-L36

before resize | after resize
-- | --
![Screen Shot 2020-04-14 at 2.39.16 PM.png](https://images.zenhubusercontent.com/5bf56fa65f3ffb2e1680062c/394c07da-5b94-4e16-b774-9da634c412be) | ![Screen Shot 2020-04-14 at 2.39.26 PM.png](https://images.zenhubusercontent.com/5bf56fa65f3ffb2e1680062c/d866d272-ce23-469a-8579-9f44dcf5e3b1)

Proposed solution:
https://github.com/canonical-web-and-design/jaas-dashboard/pull/503/files

**Comment by hatched** [comment]
It looks like this issue was created due to this fix (for another issue) https://github.com/canonical-web-and-design/vanilla-framework/commit/78f8c5c7d064e2c9d578d690956c59ac1f4b6af8

What this issue was resolving was a table without any content. We no longer have any empty tables (we have an empty table message), maybe this was an incorrect approach to resolve the issue and this 'fix' can now just simply be removed.
