### ISSUE TITLE
Disambiguate label component from buttons

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#3126]
## Pattern to amend

The styling of the label component is too close to buttons, as flagged in this issue:
https://github.com/canonical-web-and-design/ubuntu.com/pull/7741

Consider making them more distinct, e.g. by not using round corners, etc.

Previous design discussion for reference: https://github.com/canonical-web-and-design/vanilla-squad/issues/587

**Comment by spencerbygraves** [comment]
@cassiocassio @lyubomir-popov @clagom 

In relation to the comments over [here](https://github.com/canonical-web-and-design/ubuntu.com/pull/7741), the component labels were designed to be used in Vanilla docs, although we did use one recently for the "beta" label in Jaas, for speed really.

In that context there wasn't much need to make them different to buttons. I guess inevitably these will be used in other places though.

If we want these to be used more widely we should look at naming, which is currently specific to vanilla components:

- new
- deprecated
- in progress
- updated
- validated

I think "certified" and "verified" would need to be different to these.

**Comment by spencerbygraves** [comment]
Actually, we shouldn't lose these categories as they are [serving a purpose](https://vanillaframework.io/docs/component-status). So we should think about how different they need to be from buttons.

If we need labels for wider use that can be something new.

**Comment by lyubomir-popov** [comment]
the uses outside of vanilla that I've seen are:

- affirmative / reassuring highlights
- beta versions of software

In some cases, an icon might help explain the purpose, so maybe labels should support icons?
In most cases, exact colour doesn't matter, as long as it roughly matches - affirmative could be any shade of green or blue for example

in some rare cases (CVEs)? a qualitative palette of non-semantic colours might be needed, just because of the number of colours required. Ideally, a label should be able to accept such a color.

**Comment by lyubomir-popov** [comment]
Another use 

![image](https://user-images.githubusercontent.com/2741678/84761770-d4aedd00-afc1-11ea-82cc-c55f6af1fcde.png)

**Comment by bartaz** [comment]
Github in their beta design go back to rounded times of web 2.0 with full rounded ('chip') labels:

![Screenshot 2020-06-18 at 15.06.36.png](https://images.zenhubusercontent.com/593a660851aa2c30578102bb/b6b4a2a0-0421-4ac4-a197-b350dd130a41)

**Comment by matthewpaulthomas** [comment]
(The GitHub beta design _also_ greatly increases the roundedness of buttons, and flattens them too, so I’m not sure labels are any more distinct than they were before.)

> the uses outside of vanilla

For UA renewals, we added a “Renewed” label next to the newly-extended end date, which was possible because it mapped well to the “updated” class.

> in some rare cases (CVEs)? a qualitative palette of non-semantic colours might be needed, just because of the number of colours required. Ideally, a label should be able to accept such a color.

Yes, there were a few reasons we didn’t use labels for either priority or status, and one of them was that there weren’t enough distinct classes.

A couple of goofy ideas for making labels look less like buttons:
![image](https://user-images.githubusercontent.com/19801137/85222409-a874d100-b3b2-11ea-8a01-f3445b267068.png)

(For the second one I’m thinking of [perforated label rolls](https://www.ecosia.org/images?q=perforated+label+roll).)

One more thing to consider is whether we can convey whether a particular label is clickable (as I just now discovered GitHub’s are). Probably labels that are clickable should look _more like_ buttons than labels that aren’t clickable.

**Comment by lyubomir-popov** [comment]
- Validated
- In addition to @matthewpaulthomas 's label exmaple, @cassiocassio proposed matching the obliqueness of the ubuntu italic typeface
- benchmarking: https://semantic-ui.com/elements/label.html
- sufficent distinction between chips and labels, chips and buttons
- consider dismissable / clickable / non-clickable labels

**Comment by anthonydillon** [comment]
Could you add a link to what was validated?

**Comment by lyubomir-popov** [comment]
@anthonydillon no design to link to yet, we'll iterate based on the comments above.

**Comment by lyubomir-popov** [comment]
Another example from charmhub: 

<img width="263" alt="Screenshot 2020-08-13 at 10 24 02" src="https://user-images.githubusercontent.com/2741678/90117815-4a7bbe80-dd4f-11ea-93bc-4da231430c38.png">

Mixed usage (some interative, others not) is also likeley, so it needs to be considered as part of the issue.

**Comment by spencerbygraves** [comment]
@clagom @cristinadresch can we also assign a UX designer to this when we do the work please. It would be good to cover all the types of label we need.

**Comment by clagom** [comment]
Let's discuss in planning

**Comment by rayito** [comment]
From [3800](https://github.com/canonical-web-and-design/vanilla-framework/issues/3800)

After a workshop with @ziheliu214 @bartaz @lyubomir-popov @clagom and @wgx we decided the following:
- The "Label" component (.p-label) is going to be deprecated.
- The "Chip" component will take the place of the labels, with a rework and new styles. 
- A new "Badge" component will be included for the simple, numeric labels.


Regarding the new Chips, the variants would be the following:
* Static chip
    * With icons
    * With numeric badges
    * With icons and badges
* Interactive chip
    * Hover
    * Toggle select (on/off).
    * Click

**Comment by clagom** [comment]
Include #3202
@rayito to work on the specs and discuss use-cases in design assembly. @lyubomir-popov to work on the visual

**Comment by ziheliu214** [comment]
@rayito Hi since the visual issue was completed (https://github.com/canonical-web-and-design/vanilla-framework/issues/3980) what's the next step?

@lyubomir-popov and I think its good to have a small documentation to classify "badges" and "chips" following the workshop decision. And some behaviors should be captured e.g. the number badge becomes "K" when its greater than 999 etc
