### ISSUE TITLE
Can not include _base_typography-definitions.scss standalone

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/vanilla-framework#3133]
If you do this:
```scss
@import "~vanilla-framework/scss/base_typography-definitions";
```
You will get this error:
```bash
ERROR in ./src/components/Chip/Chip.scss (./node_modules/css-loader/dist/cjs.js??ref--7-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--7-oneOf-5-3!./node_modules/sass-loader/dist/cjs.js??ref--7-oneOf-5-4!./src/components/Chip/Chip.scss)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: no mixin named deprecate
        on line 21 of node_modules/vanilla-framework/scss/_base_typography-max-widths.scss, in mixin `heading-max-width--short`
        from line 6 of node_modules/vanilla-framework/scss/_base_typography-definitions.scss, in mixin `vf-b-typography-definitions`
        from line 3 of /home/ant/projects/react-components/src/components/Chip/Chip.scss
>>   @include deprecate('3.0.0', 'Max-widths should not be based on font-size. 
   -----------^
```

**Comment by bartaz** [comment]
I think the missing part is in `settings.scss`, so doing:

```scss
@import "~vanilla-framework/scss/settings";
@import "~vanilla-framework/scss/base_typography-definitions";
```

I would say that anything that imports stuff from Vanilla should import settings first, but we can add settings import inside base typography definitions to make sure it works on its own as well.

**Comment by bartaz** [comment]
@anthonydillon I have a problem reproducing this when building SCSS.

Is `@import` itself already breaking? or are you using `@include` as well?
It does break for me, but on missing placeholders, not deprecate mixin.

**Comment by bartaz** [comment]
While base styles are split into multiple files they seem to be quite dependent on one another (sometimes including each other in cycles). It's hard to untangle it to make them importable independently.

Looking at the `base.scss` it seems that the minimal include is `base_placeholders` (with `@include vf-b-placeholders`). This is marked as mandatory import/include, so it seems this is necessary for any other base styles to work.

It seems that it will also include typography definitions, so I think that instead of importing only `base_typography-definitions` directly, you should include `base_placeholders` (and `@include vf-b-placeholders`).

**Comment by anthonydillon** [comment]
Yes, you are right. It worked with:
```scss
@import "~vanilla-framework/scss/base_placeholders";
@include vf-b-placeholders;
```
