### ISSUE TITLE
The font fallback results in very thin text

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#3166]
Body text is using ubuntu Thin as a fallback, resulting in unreadable text:

![image.png](https://images.zenhubusercontent.com/59d2496bb0222d5de479ea17/e00da8ef-f71f-4da2-816d-721c120cbdf1)

**Comment by spencerbygraves** [comment]
@lyubomir-popov not sure I understand. The image above shows Ubuntu light, what's the substitute?

**Comment by lyubomir-popov** [comment]
Hmm didn't look closely enough, you're right. Apparently Light is falling back to Thin. Maybe we should just ensure light loads before thin? @bartaz ?

**Comment by lyubomir-popov** [comment]
I think it loads thin first because it is used in an h1 on the index page, and it considers it the most important thing to load

**Comment by bartaz** [comment]
For me it's the opposite, if fallback font is used it's bolder than web font:

<img width="1319" alt="Screenshot 2020-07-10 at 13 39 05" src="https://user-images.githubusercontent.com/83575/87150652-c8f9c200-c2b2-11ea-9ed4-551b61f1d0b6.png">

But this may be because I have Ubuntu font installed locally and it is used until proper light/thin version loads.

@lyubomir-popov Do you maybe have ubuntu light or thin installed in your system?

**Comment by lyubomir-popov** [comment]
Yes, I do have OS installed ubuntu in all weights. Interesting. At least most people will see it in a readible format, so that's good.

**Comment by bartaz** [comment]
Seems to be caused by fonts installed in @lyubomir-popov OS.
