### ISSUE TITLE
Amend side navigation to add additional level of depth

### ISSUE THREAD

**Issue by wgx** [canonical-web-and-design/vanilla-framework#3174]
## Pattern to amend

Navigation > Side Navigation: https://vanillaframework.io/docs/patterns/navigation#side-navigation

## Visual

Proposal (mockup)
![nav proposal](https://user-images.githubusercontent.com/930099/87916081-e1b06780-ca6a-11ea-8b93-304302d84134.png)

Annotated proposal (mockup)
![nav proposal anno](https://user-images.githubusercontent.com/930099/87916124-effe8380-ca6a-11ea-86ee-f34d05dd0926.png)

Please feel free to amend this proposal as you see fit! 

## Context

In many navigation contexts it's helpful to have an additional level of side navigation depth. In documentation, for example, the pattern: Section, Heading, Subheading is useful for organising content and allowing users to find what they're looking for as well as orient themselves. In this proposed amendment we:

- Allow users to navigate within a sub-section
- Show users their position in the overall heirarchy
- Allow users to easily see the additional items at this depth level, and
- Reduce visual noise by not exposing a sub-section hint at the top level.

(cc @bartaz ) 😀

**Comment by wgx** [comment]
FYI @clagom @cassiocassio  - navigation amendment we've discussed before, now proposed for Vanilla. 👍

**Comment by clagom** [comment]
Thanks @wgx looks inline with what was discussed previously, too. I remember @lyubomir-popov had a visual hierarchy representation of the sub-section to visually connect them to the main parent, will that be included too (needs to be updated to the latest Vanilla style)?
<img width="278" alt="Screenshot 2020-07-20 at 10 57 38" src="https://user-images.githubusercontent.com/1953388/87925224-e0d20280-ca77-11ea-90f5-95192ed86d34.png">

**Comment by bartaz** [comment]
@clagom The hierarchy (bold for the active parent pages) was initially implemented, but was removed based on design decision - I don't remember the details, was it considered too noisy? @lyubomir-popov @spencerbygraves 

Is this proposal suggesting using it to indicate active pages and their parents in the tree?

**Comment by clagom** [comment]
We can iterate on the visual after the implementation of the accordion functionality, I don't think this would be a blocker... but I thought to mention this because Lyubo's solution was visually clearer connecting the hierarchy of the indentation and levels.

**Comment by bartaz** [comment]
@clagom @wgx The description of the proposal doesn't seem to mention 'accordion' finctionality.

From what I understand what we want is having the nested levels not visible (expanded) by default, but only when parent page is active. This is currently possible and Vanilla is using it.

Top level Vanilla docs has nested levels 'hidden' (only first level with headings is visible by default):
https://vanillaframework.io/docs

<img width="334" alt="Screenshot 2020-07-20 at 12 16 53" src="https://user-images.githubusercontent.com/83575/87927076-ed0f8d00-ca82-11ea-8a98-6203b1b53f3f.png">

If you go to a specific page that has nested level, it becomes visible, only for that page:
https://vanillaframework.io/docs/base/code

<img width="334" alt="Screenshot 2020-07-20 at 12 17 45" src="https://user-images.githubusercontent.com/83575/87927146-09abc500-ca83-11ea-97b1-7887d00e92b2.png">

In case of Vanilla this is only about 2nd level, and 2nd level items are not other pages but sections of the page, but it can be done the same way for 2nd and 3rd levels of the pages with existing pattern.

I guess the only limitation is that current pattern shows all the navigation levels that are in HTML, so for nested levels to be hidden site backend or JavaScript needs to make sure to only show correct expanded levels.

We could implement a variant of the side navigation pattern that will always hide nested levels and only show them for active pages.

From that point of view it doesn't seem like any visual design change is needed, because there is nothing new introduced to the component (it's just a functionality of showing nested levels only when parent is active).

**Comment by clagom** [comment]
Sorry - I assumed this proposal included the accordion functionality (meaning, expandable menu on click on the main item to show sub-sections) but indeed it's not mentioned. I think can be a second step or the pattern, as a modular optional feature to implement it later on (especially if we have use cases and user testing inputs). The point I made on the visual still stand I find, but again can be a follow up exploration.

**Comment by bartaz** [comment]
@wgx @clagom Sorry, but it seems that from this proposal it's a bit unclear what is requested. I'm not sure if what you need is possible with current pattern (but maybe unclear from the documentation and examples) or not possible.

Could you give us some more detailed example of what you have in mind? What navigation tree you are trying to build and what seems not to be possible with current component?

Title "add additional level of depth" suggests we need more nested levels? - 3 are currently available (level "0", nested 1 and nested 2) do you need more, or is this enough?:
<img width="435" alt="Screenshot 2020-07-21 at 06 55 59" src="https://user-images.githubusercontent.com/83575/88014458-45946800-cb1f-11ea-95e5-ad9d44f1dd6e.png">

Description (and our previous discussion about 'accordion' functionality) suggest that you need some way of expanding/collapsing of the navigation. While this is not directly a feature of existing component, it is possible to achieve if 'collapsed' levels are removed/hidden with JS or in the backend.

**Comment by wgx** [comment]
@bartaz Closing for now. We need more exploration with the squad and I'll propose a new working group issue when I've gathered more requirements. 👍
