### ISSUE TITLE
"Chips" with numbers

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/vanilla-framework#3202]
It is likely people will like to add numeric chips to tabs but they do not work.

Screenshot of its use:
![image](https://user-images.githubusercontent.com/1413534/89916153-3325bf80-dbef-11ea-8f73-29cf7d315b77.png)

We could use label but I believe people will expect both "To Just Work".:
![image](https://user-images.githubusercontent.com/1413534/89916467-86980d80-dbef-11ea-94b8-8feb3e274b17.png)

Here is an example of where its usage is beginning to be imagined: 
https://app.zeplin.io/project/5f3170425822f41fc299a330/screen/5f32a3c5653dc9515831eae7

**Comment by lyubomir-popov** [comment]
My first impulse is to say this is a label. Unless anyone disagrees, I'd propose not calling this a chip because most of the chip functionality doesn't apply in this use case (interactions, dismimssing, editing in place, category/value, etc.).

**Comment by anthonydillon** [comment]
For clarity, the reason I originally went for a chip is its round and most cases the notification indicator is round. I wonder now if we should just provide this as a feature on the tab pattern.

For example:
```html
<nav class="p-tabs">
  <ul class="p-tabs__list" role="tablist">
    <li class="p-tabs__item" role="presentation">
      <a href="#section1" class="p-tabs__link" tabindex="0" role="tab" aria-controls="section1" aria-selected="true">
        Machine summary
        <span class="p-tabs__indicator">3</span>
      </a>
    </li>
    ...
  </ul>
</nav>
```

This would allow us to provide specific styling to help in different cases in a limited scope.

**Comment by matthewpaulthomas** [comment]
Counts might be used in tabs, but I think they’d be used more often inside other elements. For example, sidebar items:

![image](https://user-images.githubusercontent.com/19801137/90330256-36c89600-dfa3-11ea-851f-1befc10a8f63.png) ![image](https://user-images.githubusercontent.com/19801137/90330176-ab4f0500-dfa2-11ea-899b-efc414704fed.png) ![image](https://user-images.githubusercontent.com/19801137/90330099-34b20780-dfa2-11ea-9758-9bee785bf64b.png) 

Arguably, text fields:

![image](https://user-images.githubusercontent.com/19801137/90330056-d84ee800-dfa1-11ea-9702-b9d9f4976bbb.png)

And coincidentally, for certified hardware on ubuntu.com, I’ve proposed counts in an inline list:

![image](https://user-images.githubusercontent.com/19801137/90330316-cec67f80-dfa3-11ea-9adc-f6f9e3ce4c37.png)

**Comment by lyubomir-popov** [comment]
We need this in Maas as well:

![image](https://user-images.githubusercontent.com/2741678/103630371-76375500-4f39-11eb-891d-f3e3fbf7f377.png)

**Comment by lyubomir-popov** [comment]
Just found a workaround for chips, we cna use the following two classes:

![image](https://user-images.githubusercontent.com/2741678/103631331-bf3bd900-4f3a-11eb-9d20-2acb820129a4.png)

But this can only be a stopgap solution, there should be something tailored to the tabs specifically that works with icons, chips and regular text.

**Comment by clagom** [comment]
We have this in JAAS:
![image](https://user-images.githubusercontent.com/1953388/125939439-aac1c418-0582-4d29-8494-8e71add2da45.png)
And @anasereijo has a similar needs in the side-nav filter on certifications.
Sounds like we all need the same component :)

**Comment by bartaz** [comment]
We currently have chips (https://vanillaframework.io/docs/patterns/chip):

<img width="137" alt="Screenshot 2021-07-16 at 13 18 42" src="https://user-images.githubusercontent.com/83575/125939797-a136ec0b-0c5a-4653-8ed8-a6e57186df61.png">

That could be technically used with just numbers (but are not round), but also are meant to be interactive (clickable), and they don't have multiple colors.

<img width="63" alt="Screenshot 2021-07-16 at 12 55 38" src="https://user-images.githubusercontent.com/83575/125939799-cad923fa-4edc-4a18-9330-508ead8992dc.png">


We have labels (https://vanillaframework.io/docs/patterns/labels): 


<img width="70" alt="Screenshot 2021-07-16 at 13 21 53" src="https://user-images.githubusercontent.com/83575/125940293-72f2150f-1325-41a1-a763-b3f99fe82871.png">
<img width="42" alt="Screenshot 2021-07-16 at 13 22 12" src="https://user-images.githubusercontent.com/83575/125940290-67973e84-4a11-4713-bf03-bad3f5ed877b.png">

Labels are separately explored also in issue canonical-web-and-design/vanilla-framework#3800 because their usage is currently unclear.

But visually it seems that "circle with number" should be similar to an icon with a number in it:
<img width="66" alt="Screenshot 2021-07-16 at 13 22 26" src="https://user-images.githubusercontent.com/83575/125940288-dadb4ca4-b2f2-49c8-8e4b-1a116478682a.png">


It seems that we need a status "circle with a number" component to show how many of a thing is relevant to user (filtered, errored, etc). We should decide if any of current components (chips, labels) could be used for that, or do we need a new one specifically for this use case.

**Comment by lyubomir-popov** [comment]
This is blocked until the badges component is implemented.

**Comment by clagom** [comment]
WG: this component is now called "badge" and has been approved and ready to build https://app.zenhub.com/workspaces/-vanilla-squad-59438c953747487777fbe484/issues/canonical-web-and-design/vanilla-framework/4013
