### ISSUE TITLE
In page anchors dont work in docs on mobile Chrome

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/vanilla-framework#3292]
The in pages anchors in the typography page doesn't work.

For example: https://vanillaframework.io/docs/base/typography#the-value-of-1rem

Then select another navigation item.

**Comment by lyubomir-popov** [comment]
@bartaz can you replicate this? Tehy work fine in FF and chrome on mac when I click them.

**Comment by bartaz** [comment]
Seem to work for me as well.

Could you give us more details @anthonydillon? What page you are on, what exactly you are clicking, in what browser?
Could it be related to CodePens loading slowly - does it work after some time (when CodePens are fully loaded)?

**Comment by anthonydillon** [comment]
Ah, it looks like it might be more complicated as it's just on mobile Chrome.

**Comment by bartaz** [comment]
Ah, mobile. Yes, I can confirm this happens to me as well.
I remember QAing this when side navigation was built, but maybe we changed something in the meantime. It seems like mobile chrome is trying to scroll navigation instead of the page...


Ah, damn... It's because we disable scroll on body (overflow: hidden) to prevent body from being scrolled when sidenav is open. Only when sidenav is closed body can be scrolled. But this makes anchors in sidenav broken. We need to remove the JS that disables scroll on body when sidenav is open.
