### ISSUE TITLE
Consider using focus-visible

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/vanilla-framework#3352]
Chrome adds support for focus-visible in recent 86 version, should be followed by Firefox soon.

This allows to show focus styles only on keyboard focus, not when clicking.

It seems to be possible to keep fallback :focus support for older browsers and override it with :focus-visible for those that support it.

https://matthiasott.com/notes/focus-visible-is-here
https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible

**Comment by barrymcgee** [comment]
@bartaz Related to this - I investigated [this bug](https://github.com/canonical-web-and-design/jaas-dashboard/issues/711) this morning and found the cause is that Vanilla focus styles only apply to anchor tags (`a:focus {}`).

Applying them without qualification (`:focus {}`) will apply the styles to anything the browser deems to have focus.
