### ISSUE TITLE
Modular table - Sticky table headings

### ISSUE THREAD

**Issue by long-chung** [canonical-web-and-design/vanilla-framework#3434]
A pattern in Vanilla needs to be flexible enough that it can be used across a wide range of scenarios and shouldn't be constrained to a specific number of applications.

## Screenshot

![Sticky_Header.png](https://images.zenhubusercontent.com/5f1ec667037c164bb1ed32d9/a73999ba-7e2d-44c2-b075-7c01a6c44a80)

## Context

In JAAS we show different tables in the same view. Some of these tables can be quite long so as you scroll down the page you lose the table headings and the context of the information on the table/s.
Would like to propose that the table headings remain fixed to the top of the content area until its scrolled passed and then the table below's heading will remain fixed.

## State

Fixed table heading on scroll

## Progressive enhancement

A pattern should be designed small screen first. How does this pattern scale up?
How will this pattern degrade on less competent browsers?

**Comment by lyubomir-popov** [comment]
- Agreed to do this
position: sticky on the th, no js required

**Comment by bartaz** [comment]
This have been through WG before, but because it needs UX work we should pass it though our new process.

**Comment by clagom** [comment]
Discussed in the new WG, validated again as a valid use case. 
Requires changes and integrations UX and UI specs wise in the modular table pattern document.

**Comment by SirSamTumless** [comment]
@AnnSoMuller and @danielmutis We've got you working on this next iteration (24th)

**Comment by danielmutis** [comment]
In terms of UX, here is what I have concluded:

**Sorting**
After doing some [benchmarking](https://miro.com/app/board/o9J_lBLevYg=/) of ways this issue has been approached, I think the correct behaviour is to still allow sorting as they scroll down the table, but without scrolling them back up (i.e. keeping their current scroll position on the table). This is how Apple does it in Finder, as well as for example Spotify and Dropbox. Google scrolls you back up, although users may not realise that's what is happening. In this way it's easier for the user to identify what has changed. 

**Interaction with other sticky things**
The use cases for this extension of the table are quite broad, and I think limiting the interaction with other elements on the page would be too broad for each context. If the table header has to interact with a sticky nav, my recommendation is that the nav remains sticky, and the table header stays visible until the user has scrolled past the table. If there is more than one table with a  fixed header, they should interact as per this [example](https://adrianroselli.com/2020/01/fixed-table-headers.html).

**Mobile**
On mobile, if there are more sticky things on the page, this could eat up quite a bit of vertical space. It may be best to not have sticky table headers on mobile if there is a concern for vertical space. Otherwise we can also design a narrower table header on mobile with less padding, although the default behaviour should be to not have them unless specified.

**Comment by cristinadresch** [comment]
@danielmutis @ziheliu214 @lyubomir-popov @sowasred2012 @bartaz moving this into review, if you could all have a look please and +1

**Comment by lyubomir-popov** [comment]
We discussed this with @danielmutis yesterday and I agree with his findings.

**Comment by clagom** [comment]
Thanks @lyubomir-popov, does this still need the Reviews in the tags or can be moved to implementation (if necessary)?

**Comment by SirSamTumless** [comment]
@danielmutis Is there a spec ready for build?

**Comment by danielmutis** [comment]
@SirSamTumless my understanding was that this didn't need a full spec. I think it would be good to have a visual exploration of how this would look on mobile to accompany what Long did for JAAS. Do I need to produce a spec? Maybe just add info to the table spec with my findings + visuals?

**Comment by danielmutis** [comment]
I have added a section to the [discourse table spec](https://discourse.ubuntu.com/t/sticky-header/23084).
