### ISSUE TITLE
Add padding-top to responsive table cards 

### ISSUE THREAD

**Issue by bethcollins92** [canonical-web-and-design/vanilla-framework#3481]
## Pattern to amend

Table - Responsive
`p-table--mobile-card`

## Visual

![image](https://user-images.githubusercontent.com/58959073/103903857-5dbf6a00-50f4-11eb-9985-f7b3aed8b14b.png)

## Context

Discussed with @spencerbygraves, adding `padding-top: 1rem` to the cards would work better than no padding. See example below from CUBE: 

![image](https://user-images.githubusercontent.com/58959073/103904237-edfdaf00-50f4-11eb-8fc1-debca97f3716.png)

**Comment by bartaz** [comment]
@lyubomir-popov If we are fine with the proposed change it probably can be a quick fix rather than WG proposal, right?

**Comment by lyubomir-popov** [comment]
1 rem seems a bit much to me - we have .4rem nudge on the text already, so maybe just .5rem padding-top?

![image](https://user-images.githubusercontent.com/2741678/103914752-38d1f380-5102-11eb-910f-5191e3bde064.png)


Also, this component currently doesn't stick to the baseline grid. Probably because the line boxes on the two different font-sizes are misaligned and the combined linebox is taller than 1.5rem. You can see the text n the right starts to drift after the first 2 lines:
![image](https://user-images.githubusercontent.com/2741678/103915048-92d2b900-5102-11eb-926d-68196b158b5f.png)

I experiomented quickly, and removing the bottom padding of .1rem on the td sees to get it almost right - 
![image](https://user-images.githubusercontent.com/2741678/103914988-7afb3500-5102-11eb-81c8-7837c07ef145.png)

And lastly, the headings do not match the heading style - they are thinner and larger (small instead of x-small text fontsize), so ideally that should also be addressed.

**Comment by lyubomir-popov** [comment]
@bartaz I agree it doesn't need to be a proposal, maybe convert the issue to an epic and we can deal with them one by one?

**Comment by bartaz** [comment]
@lyubomir-popov to propose a new design for mobile card tables.

**Comment by bartaz** [comment]
Mobile table has already been redesigned. This can be closed now.
