### ISSUE TITLE
Grid breakout - collect examples

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#3505]
Collect examples from snapcraft and other products of:

- [ ] super-dense charts
- [ ] maximisable content, e.g. maps, card grids

- [ ] with and without Left hand navigation, column navigation
- [ ] with and without metadata side column (L & R), e.g. Charmhub

**Comment by lyubomir-popov** [comment]
@tbille Made an issue in our repo, hope that'a ok. What I'm after is one or two examples from snapcraft (or a dashboard) of content that would benefit from placement that extends beyond the grid (if such examples exist, none is also a valid answer :)

This is what I'll use as a placeholder, to give you an idea:
![image](https://user-images.githubusercontent.com/2741678/105372483-8d469a00-5bfd-11eb-83f1-a866a328bb67.png)

Examples of what might qualify:
![image](https://user-images.githubusercontent.com/2741678/105370646-b108e080-5bfb-11eb-8f5e-6c9f86ce7054.png)

something like this, but with more data along the x axis
![image](https://user-images.githubusercontent.com/2741678/105370677-b9611b80-5bfb-11eb-8029-a8411d5562e9.png)

**Comment by matthewpaulthomas** [comment]
Just production examples, or do wireframes count as well? Here’s one I did in 2017 for Snapcraft:

![Option Caramel](https://user-images.githubusercontent.com/19801137/105627052-29ee7f00-5e2c-11eb-95d7-87341854971d.png)

The idea was that by using the full viewport width, we could show [small multiples](https://en.wikipedia.org/wiki/Small_multiple) for all your snaps at once, so that you could compare them vertically. Navigation into/between snaps would be handled by the first filter menu, rather than with a sidebar.
