### ISSUE TITLE
Contextual menu: provide overlapping variant

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#3514]
In cases where a contextual menu is triggered by a button whose text repeats one of the values inside the dropdown it produces on click, would it be a good idea to make the menu overlap the button?

From what I can find (point 6 in this [nngroup article](https://www.nngroup.com/articles/drop-down-menus/)), a dropdown should not obscure a label that provides context, but in the case of repeating a value, this seems not to apply.

**Comment by matthewpaulthomas** [comment]
As @bartaz wrote in #3513, what you’re describing is what HTML calls `<select>`, Apple lately calls a [pop-up button](https://developer.apple.com/design/human-interface-guidelines/macos/buttons/pop-up-buttons/), and Microsoft misleadingly calls a [combo box](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/combo-box). I call it a “radio menu”, because it’s the menu equivalent of a set of radio buttons, where there’s (almost) always one current selection.

In the closed state, the menu shows what that current selection is. In the open state, the reason the menu covers the button (except on Windows) is so that the current item can be positioned exactly over top of where it was when the menu was closed — slightly simplifying the UX, reducing errors (because a double-click is a no-op), and allowing easier incrementing/decrementing. If you aren’t going to do that, you’re inviting accidental selections.

I suggest that the docs encourage people to use a `<select>` for this whenever possible, because it’s:
- more accessible generally — for example, it responds correctly to Esc, Space, Enter, Up, Down, Tab, and dragging, none of which Vanilla’s menu does
- much faster to use when the menu happens to be taller than the window, or close to the edge of an unmaximised window (because it can expand beyond the edges of the window)
- more predictable when the menu happens to be close to the edge of the screen (changing size and/or direction if necessary).

It might be necessary to use a custom replacement if your menu really needs something that `<select>` doesn’t provide — for example, menu items that contain icons, sparklines, or colour swatches.

The docs certainly shouldn’t give an example of a menu that overlaps its parent but has commands in it. That would invite accidental selection of commands.

**Comment by lyubomir-popov** [comment]
Thanks for the detailed reply @matthewpaulthomas. Looking at the wai-aria [spec](https://www.w3.org/TR/wai-aria/#select), there seem to be subtle distinctions within the 'select' role, with combobox, radiogroup and others having distinct meanings:
![image](https://user-images.githubusercontent.com/2741678/105972922-0cb3ed80-6084-11eb-9e23-4c2dc87b485d.png)

There's also a long list of keyboard interactions that needs to be supported (here's for example the combobox role's [keyboard interactions](https://www.w3.org/TR/wai-aria-practices/#textbox-keyboard-interaction)). I'm going to close this as we have many higher priority things to focus on at the moment.
