### ISSUE TITLE
Search component: Excess right padding even when there is no reset button

### ISSUE THREAD

**Issue by carkod** [canonical-web-and-design/vanilla-framework#3626]
**Describe the bug**

Excessive `padding-right` even when reset button is removed. This causes input text and placeholders to be "eaten up" by the right space.

**To Reproduce**

Reproducible example https://codepen.io/carkod/pen/LYbqZYZ

**Expected behavior**

Possibility of overriding or complete removal of additional space when there is no reset button

**Screenshots**

<img width="204" alt="Screenshot 2021-03-12 at 11 55 13" src="https://user-images.githubusercontent.com/14939793/110937271-0aeb7400-832a-11eb-8b57-84d7ba9cf65f.png">

**Desktop (please complete the following information):**

All standard browsers

**Comment by lyubomir-popov** [comment]
This is not technically a bug, because you're partially modifying the component. We could turn this into an optional feature, but we'd have to consult UX first. I'll label it WG.

**Comment by anthonydillon** [comment]
Why would you remove the standard part of the search box pattern? Feels like clear would be beneficial.

**Comment by carkod** [comment]
> Why would you remove the standard part of the search box pattern? Feels like clear would be beneficial.

Ok. I have been investigating the additional space, and it seems to be right. Do we want to make the rest button optional? if not we can just close this ticket then

**Comment by clagom** [comment]
@cassiocassio @anasereijo worked on the search with a different use of the reset button (to close the search focus): https://app.zeplin.io/project/5ffdb21a3714151de9cf750c/screen/5fff03c52885841ced879a74

The @ziheliu214 modular Search and Filter pattern has the reset button: https://zpl.io/a88DZDQ

As @anthonydillon said, we need to work on UX specs and guidelines.

**Comment by lyubomir-popov** [comment]
Interesting opinion: https://ux.stackexchange.com/questions/75768/is-a-clear-input-button-only-for-search-fields )the accepted answer)

**Comment by cassiocassio** [comment]
This is very old Jacob, not sure I completely agree - but does pose the question __why?__ would users want to clear...

"The Web would be a happier place if virtually all Reset buttons were removed. This button almost never helps users, but often hurts them."

https://www.nngroup.com/articles/reset-and-cancel-buttons/

- clear/reset does seem useful - albeit dangerous - in a large fieldset, but less so in a single search input field

**Comment by clagom** [comment]
Should this then become a proposal with UX reasoning on removing the reset button altogether from:
- Default search 
- Search and filter pattern https://zpl.io/a88DZDQ

As @anthonydillon said, we need to work on UX specs and guidelines, at the moment it seems we are leaving this issue on "I like it" "don't like it" level.

**Comment by cassiocassio** [comment]
The reason the X is there - and this was part of the conversations and series of wireframes and designs that led up to this - was that this is where were are heading - a proposal for next cycle - to provide useful as you type search feedback.

<img width="1135" alt="Screenshot 2021-03-31 at 14 57 30" src="https://user-images.githubusercontent.com/4593556/113156412-dfc1b980-9231-11eb-9131-0e2fb3ab8f46.png">

The initial build of this used the default component, with X clearing the field - AND also had the model+lightbox behaviour. But the designs and the plan were always for the X to close / escape the focus. 

As soon as you add the lightbox behaviour and the state-changing animation, it feels much more natural to interpret the X as close than Reset. We changed it becuase it no longer did what you expect.

I think that would become more obvious  when the search drop down suggests resutls. Remove it before then if you think it's a problem.

We never had any intention of changing the Reset-X behaviour elsewhere.

======


Separate question: we should remove the X everywhere has 2 arguments

1. It's just fiddly and not efficient, because your fingers are already on the keys and it's a mouse action
2. Jacob's fieldset argument referenced above

Quick benchmarking FWIW

https://miro.com/app/board/o9J_lMELD3A=/

**Comment by clagom** [comment]
@SirSamTumless this is ready for planning

**Comment by rayito** [comment]
I wrapped up a quick research and some conclusions about this topic here:

https://docs.google.com/document/d/1J7TXFeG1Yaszd17S509yzgqomV4n7seFS3avP9glcn8/edit?usp=sharing

Please feel free to comment.

**Comment by elioqoshi** [comment]
Thanks @rayito !

I agree with your thinking here, and as long as we don't have any good particular scenarios to omit the clear button, we should stick with it. 

However I am worried about the alignment of the search magnifying glass icon on the right, as well as the clear icon on the right too. I don't want to open another can of worms, but I am curious what's the reason we keep the search icon on the right, rather than the left (like most design systems, including your Netflix example). I don't think having an interactive clear button next to a non-interactive search would be idea. Could you visualise the behaviour you are proposing?

**Comment by rayito** [comment]
As discussed in the UX channel, the decision is to keep the clear button for all search/filter fields.

We need to have a look at the design and behaviour mentioned by @elioqoshi, but that will be a differten task.
