### ISSUE TITLE
Back to top does not match background color

### ISSUE THREAD

**Issue by huwshimi** [canonical-web-and-design/vanilla-framework#3667]
**Describe the bug**

When using the back-to-top link on a background that isn't white then the "Back to top" text has a mis-matched background colour.

**Screenshots**

<img width="145" alt="Screen Shot 2021-03-26 at 9 24 47 am" src="https://user-images.githubusercontent.com/361637/112551455-2324be00-8e15-11eb-9062-38db9c6c92a0.png">

**Comment by bartaz** [comment]
@lyubomir-popov Could you have a look if design could be improved to avoid the need of putting solid background on top of the border?

**Comment by lyubomir-popov** [comment]
@bartaz We have an icon called back-to-top, so maybe remove the right margin, set margins between elements to 1rem, add the icon at the end?

![image](https://user-images.githubusercontent.com/2741678/113877522-b0bac300-97b0-11eb-9cb9-b07703810718.png)

**Comment by anthonydillon** [comment]
You could try and use a `clip-path`. I used that on canonical.com slanted strips so any strip below shows through.

**Comment by bartaz** [comment]
> You could try and use a `clip-path`. I used that on canonical.com slanted strips so any strip below shows through.

I looked a bit into clip-path, but I'm not sure we can apply it easily here. Because the part we want to clip depends on the text content "Back to top", it's size/positon may change with screen size, etc. There doesn't seem to be a nice way to define a clip path that flexible.

With the new design it should be fairly easy to achieve with `::before` element adding the line and icon on the right.
