### ISSUE TITLE
p-table--mobile-card looks too tight when $multi is less than 2

### ISSUE THREAD

**Issue by sowasred2012** [canonical-web-and-design/vanilla-framework#3789]
**Describe the bug**

On the MAAS sprint we thought it would be a good idea to add the `p-table--mobile-card` class to some of the tables, but it looks very tight:

![Screenshot from 2021-06-14 14-59-16](https://user-images.githubusercontent.com/2376968/121904459-1da68800-cd21-11eb-836a-c6a970b7a996.png)

MAAS have `$multi` set to `1`, setting it back to the default improves things:

![Screenshot from 2021-06-14 14-52-43](https://user-images.githubusercontent.com/2376968/121904587-37e06600-cd21-11eb-8aff-87d5f60afc35.png)

**Comment by lyubomir-popov** [comment]
I've looked into this, and I think the current situation in vanilla is the smallest compromise. Yes, it is tight, but the inention of the multiplier is to make things as dense as possible, barring any overlaps.


If we did increase the distance between label and value, the value will become closer to the next cell's label and look visually grouped with it. (Third example in the screenshot, highlighted by a pink box):


![image](https://user-images.githubusercontent.com/2741678/122765558-8b5e3100-d298-11eb-978c-90a2930530db.png)

We can of course compensate for that by increasing the space between text and borders, but this gets us back to the vanilla default spacing, thereby defeating the purpouse of having a density multiplier.

That said, I wonder if local overrides might be causing the spacing t obe even tighter than the stock vanilla version. Comparing the first two columns in the screenshot, the borders go out of sync after the second row, meaning the cells are smaller (but this may also be due to scaling of the original screenshot attached). So I would check whether the mass situation precisely m atches the [vanilla example](http://192.168.64.2:8101/docs/examples/patterns/tables/table-mobile-card).
