### ISSUE TITLE
Define when to use / when not to use then .p-label class

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#3800]
Once `.p-label` (without mdifier) has been added to vanilla, we should take some time to define when to use, when not to use, etc. This is just a placeholder issue to keep this on the radar.

**Comment by long-chung** [comment]
@lyubomir-popov as requested, here's a short summary for .p-label (Badges)

**Introduction**
Badges are labels which hold small amounts of information and are used to visually label UI objects for quick recognition. 
A Badge draws attention to new or categorised content elements that might otherwise be missed.


**Considerations**
Keep in mind that badges increase the amount of visual noise, particularly when combined with other visual labelling elements, so use them in moderation.

Confusion with buttons. Avoid Badges if they might appear in the same area of the page as buttons.
Don’t mix interactive and static Tags and Badges. 

Don’t overdo it. If everything on a page is called out as important, nothing commands unique attention.

Badges should be styled distinctly from a button or a tag. Tags have a lozenge shape as used in the search and filter pattern. Buttons have a much larger surface and are usually placed in an area where there is an expected call-to-action.

**Comment by lyubomir-popov** [comment]
@long-chung thanks, could you include some benchmarking? E.g. references to documentation of this in semantic-ui, material design, etc.

**Comment by lyubomir-popov** [comment]
Great reference links, thanks @long-chung !

**Comment by rayito** [comment]
First approach to a general convention: https://github.com/canonical-web-and-design/vanilla-framework/issues/3800

**Comment by cristinadresch** [comment]
@rayito if you could also present this during design assembly please

**Comment by clagom** [comment]
WG is going to work together during a session about this issue after the roadmap sprint.

**Comment by clagom** [comment]
Consider these points from the issue
#3126

**Comment by rayito** [comment]
After a workshop with @ziheliu214 @bartaz @lyubomir-popov @clagom and @wgx we decided the following:
- The "Label" component (.p-label) is going to be deprecated.
- The "Chip" component will take the place of the labels, with a rework and new styles. 
- A new "Badge" component will be included for the simple, numeric labels.


Regarding the new Chips, the variants would be the following:
* Static chip
    * With icons
    * With numeric badges
    * With icons and badges
* Interactive chip
    * Hover
    * Toggle select (on/off).
    * Click
