### ISSUE TITLE
Side navigation collapse/expand sections

### ISSUE THREAD

**Issue by cristinadresch** [canonical-web-and-design/vanilla-framework#3817]
Having the ability to collapse/expand sections in the left nav would allow users to see more of the navigation when there is a long list of menu items. 

This should work for both long pages with single URL e.g. [k8s survey](https://juju.is/cloud-native-kubernetes-usage-report-2021), as well as a regular docs page where each section/menu item is a new URL e.g. [operator framework](https://juju.is/docs/sdk)

![Screenshot 2021-06-28 at 11.00.28.png](https://images.zenhubusercontent.com/5c73e557b33938548e4df8a3/b7588902-7a65-4dc0-abd5-68ea3d3f9f4c)

**Comment by clagom** [comment]
See #3174

**Comment by clagom** [comment]
UX to collect the definition we worked on so far and pass to visual

**Comment by danielmutis** [comment]
The conclusions of this issue are on this [zeplin](https://zpl.io/29d1P4y).

**Comment by lyubomir-popov** [comment]
@danielmutis not entirely clear on what you mean about the horizontal line - it is a way to create grouping, i.e. the items above are more related to each other than to  the ones that follow. Using them to also indicate end of a nesting level seems a bit redundant to me.

**Comment by danielmutis** [comment]
@lyubomir-popov thanks for the feedback. I think the issue is when an item that can be expanded is followed by one of the next level that can't be expanded (see below). In this case the item "Device store D1" seems to belong to the list of items that was expanded, when it is not. 

<img width="612" alt="Screenshot 2021-08-02 at 14 39 31" src="https://user-images.githubusercontent.com/59825615/127870910-6f33141a-9365-4135-a1b9-70807779f16a.png">

**Comment by lyubomir-popov** [comment]
It looks like a sibling of Settings and child node of Store A2 - is that not the case? Might be easier to discuss this in a call, ping me when you're available.

**Comment by ziheliu214** [comment]
I have a few questions:

1) does that mean we will prioritize displaying items "snap, models, members, settings" above the expandable item, so we don't get too many horizontal dividers?
2) I understand the use of horizontal divider is to segment items and expandable items from the same level, then this case the second divider is it still necessary?
<img width="256" alt="Screenshot 2021-08-02 at 18 10 16" src="https://user-images.githubusercontent.com/61144986/127898836-3e3d1cb8-065e-4780-a724-2d040f5971b5.png">
3) let's have a discussion in tomorrow's Design Assembly.

**Comment by danielmutis** [comment]
**Amended conclusions:**
Updated [zeplin](https://zpl.io/29d1P4y).

Summary:
* Only items on level 1 and 2 can be expandable, so that the items of level 2 expanded can be aligned with level 3.
* Items that expand don’t open a page, so they won’t look selected when expanded.
* Multiple nav items can be expanded at once. The items in the nav will be collapsed by default. The UXer can decide whether they wan’t to change this default behaviour on a case by case basis.
* When an item has an icon in the nav, the chevron will be added immediately before the icon (see Zeplin).
* When there is a mix of icon and no icon, and expandable and non expandable items, the left alignment of each level will be preserved.

**Comment by clagom** [comment]
Nice work @danielmutis, did we also involve devs?

**Comment by sowasred2012** [comment]
Looks good, but I wonder whether, when there is a chevron and an icon increasing the left indent on all nav items on all levels, the third level will look really cramped/each item will wrap at every word - the side nav on the application layout already has a lot going on: 

![Screenshot from 2021-08-04 10-51-51](https://user-images.githubusercontent.com/2376968/128161120-361cf4b6-391e-4c8d-831f-94d413fc5580.png)

**Comment by lyubomir-popov** [comment]
The width of the sidenav here isn't ptimal, I'm working on the visual design for this and will make sure this is addressed there.

**Comment by ziheliu214** [comment]
> **Amended conclusions:**
> Updated [zeplin](https://zpl.io/29d1P4y).
> [Sketch file.](https://drive.google.com/file/d/14WpVOkkko-ZoRx2yYCy1aXPdzf4fGhg4/view?usp=sharing)
> 
> Summary:
> 
> * Only items on level 1 and 2 can be expandable, so that the items of level 2 expanded can be aligned with level 3.
> * Items that expand don’t open a page, so they won’t look selected when expanded.
> * Multiple nav items can be expanded at once. The items in the nav will be collapsed by default. The UXer can decide whether they wan’t to change this default behaviour on a case by case basis.
> * When an item has an icon in the nav, the chevron will be added immediately before the icon (see Zeplin).
> * When there is a mix of icon and no icon, and expandable and non expandable items, the left alignment of each level will be preserved.

late reply, yay love this one!
