### ISSUE TITLE
Tab background covers <hr>

### ISSUE THREAD

**Issue by huwshimi** [canonical-web-and-design/vanilla-framework#3878]
**Describe the bug**

Vanilla 2.31.0 adds a background to tabs that covers a `<hr class="u-no-margin--bottom">` placed before the tabs.

**To Reproduce**

https://codepen.io/huwshimi/pen/oNWwGjq

**Screenshots**

<img width="421" alt="Screen Shot 2021-07-19 at 4 25 13 pm" src="https://user-images.githubusercontent.com/361637/126112952-23abed8b-4782-423f-8e4b-a409c06df37d.png">

**Comment by lyubomir-popov** [comment]
This is due to u-no-margin-bottom applying a negative 1px margin-bottom on the hr, which is done to keep it form offsetting elements  underneath from the pixel grid. We can either:

- apply `z-index: 1;` to the hrs in vanilla, which sorts this out
- remove the negative bottom margin and live with the fact that `hr`s upset the vrtical rhithm. 

I'd vote for the former. @sowasred2012 what do you think?

**Comment by sowasred2012** [comment]
@lyubomir-popov I was originally thinking the latter, and accepting the pixel shift it would introduce - but the z-index solution looks like a cleaner solution, just gotta check it doesn't interfere with other z-indexes.

**Comment by Caleb-Ellis** [comment]
This issue is still valid when a tab is focused, sorry! A simple fix would be increasing the z-index of the hr since a focused tab has a z-index of 1.

![Screenshot 2021-08-04 at 18-16-08 Machines bolla MAAS](https://user-images.githubusercontent.com/25733845/128148013-535d7d5a-35c2-40bf-9264-296a4edf865a.png)
