### ISSUE TITLE
Paragraph max width causing odd whitespace in docs

### ISSUE THREAD

**Issue by hatched** [canonical-web-and-design/vanilla-framework#3992]
See: https://vanillaframework.io/docs/patterns/accordion

![Screen Shot 2021-09-21 at 12 57 29 PM](https://user-images.githubusercontent.com/532033/134231364-9bb609da-8327-4d9d-be72-08640632fbce.png)

**Comment by lyubomir-popov** [comment]
@hatched this is a recurring complaint. It feels tidier if things that happen to sit next to each other have matching widths, and doing that is fine - as long as it doesn't stretch elements beyond what is considered optimal for each element. For text specifically, there's a long-standing typographic best practice of limiting to 12 words or 75 characters (+/-3 words, depending on the situation). This is done for readability. For example, locatingg the beginning of the next line of text gets progressively harder as the line lenght increases. 

Since those reasons have to do with readability, they take precedence over cosmetic concerns like matching the width of another arbitrary element.

**Comment by hatched** [comment]
I'm not sure about disregarding cosmetic concerns over a hardline approach to line lengths, especially if it's a recurring complaint 😉. The fact is that it simply doesn't look good when you have paragraph text interspersed with content that's of a wider width. So if we must stick with a character limit in a `p` then maybe we should reduce the full width of that second column as well.

Looking around at other approaches to this problem it seems that others prefer an 800px width to 720px(ours). This would also be a more agreeable width to bring the other content down to.

#### p and main at 800px.

![Screen Shot 2021-09-28 at 1 39 22 PM](https://user-images.githubusercontent.com/532033/135154639-15039184-a934-43cb-985e-7d65e5b10561.png)

**Comment by lyubomir-popov** [comment]
We actually want the content column to bhe wider to accomodate examples that need the space - for example the grid examples. Currently the iframe forces them into mobile mode. We cannot compromise on the needs of different elements to make them match each other's widths. There are other ways to improve how these fit together, like better use of vertical white space between elements, etc - we're going to revisit this when we complete the design system piece of work. Altering the paragraph max-width is not the right way to do this.

**Comment by spencerbygraves** [comment]
@hatched in this case I think Lyubo is right to say that the text and examples should be separate. We need the width for some examples but we also need a sensible line length for readability.
