### ISSUE TITLE
Update switch toggle component visuals

### ISSUE THREAD

**Issue by elioqoshi** [canonical-web-and-design/vanilla-framework#4001]
I usually tend to avoid visual topics, but figured I should bring this up since several others also mentioned it.

Our switch component (also known as toggles in other design systems) has been rectangular for quite some time now. I am not sure what the reasoning behind that is, but it's clear that with some lightweight benchmarking it's hard to find a similar approach in other design systems.
![image.png](https://images.zenhubusercontent.com/5a5649f54b5806bc2bc23b6d/816f1bce-d1c5-4081-aad1-3f71a4094e66)

So in the spirit of making Vanilla "edgier", as some people worded so eloquently, it would be great to revisit the visuals of the toggle. We could also do some user testing to further support any design 

## [Atlassian Design System](https://atlassian.design/components/toggle/examples)
On:
![image.png](https://images.zenhubusercontent.com/5a5649f54b5806bc2bc23b6d/6ec866c0-4659-4615-8f80-c6d0ba177dd8)
Off:
![image.png](https://images.zenhubusercontent.com/5a5649f54b5806bc2bc23b6d/da8f5d8b-2418-4913-ba7d-3aa08066a93a)

## [Carbon Design System](https://www.carbondesignsystem.com/components/toggle/usage/)
![image.png](https://images.zenhubusercontent.com/5a5649f54b5806bc2bc23b6d/ba235b6a-3897-42c7-81f3-459d79b377b4)

---

A good place to illustrate this is Components Gallery, which summarizes 36 design system with toggle switches and how they look and behave. A glance on there makes it clear that we are trying to differentiate ourselves. I am not sure if that's helpful in this case though, as users likely recognize the toggle switch less as more conventional alternatives.

**Comment by anthonydillon** [comment]
A little background here (I feel old) is that we used the Unity switcher component when developing the Vanilla one as we wanted to maintain a look and feel better the OS and the website. Of course, this has since changed and been replaced with Gnome which use round switcher:
![Screenshot from 2021-09-28 09-20-39](https://user-images.githubusercontent.com/1413534/135051258-f3d3ceb0-d3f9-4131-b991-dbbf983342c4.png)

Therefore, maybe we should adopt this styling. I like the idea that Ubuntu/Gnome users feel "at home" on the Ubuntu website.

Two other aspects to consider:
- Mark a pending/loading state of switch
- Disabled state of switch.

**Comment by elioqoshi** [comment]
@lyubomir-popov I think we can close this, right?

**Comment by lyubomir-popov** [comment]
yes
