### ISSUE TITLE
Add table heading and small  text to text with margin component

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#4011]

**Comment by lyubomir-popov** [comment]
@long please review when you get a chance - https://www.figma.com/file/H6MSsN3taoXXOJCPUbIImQ/Design-System-Library?node-id=93%3A1056

**Comment by long-chung** [comment]
@lyubomir-popov because these aren't using any text styles, if you type in some text and then change the text style (component) in the drop down you lose any text that you have written.

**Comment by lyubomir-popov** [comment]
Good point, I was wondering why that happens.

**Comment by lyubomir-popov** [comment]
Fixed. If you could take another look so I can close this.

**Comment by long-chung** [comment]
@lyubomir-popov it doesn't seem to be fixed when I test it by dragging the component on to a board.
I just realised the reason why the text reverts back to its default is because all the placeholder text is different from each other in the variant.
This is happening with every variant that has different text for example "Button with margin" will do the same thing if you change the label and switch it to "button default".

**Comment by lyubomir-popov** [comment]
@long-chung you're right, renaming all text objects to "text" fixed it. Thanks for the trouble shooting. Can you take one final look and if it's ok add a design +1
