### ISSUE TITLE
Local modification to the docs navigation on Juju

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/vanilla-framework#4121]
**Describe the bug**
When visiting the [Juju docs](https://juju.is/docs) the side navigation is overflow hidden. Which is [locally styled](https://github.com/canonical-web-and-design/juju.is/blob/7af548bbeff3426e7a38f155efbd2087c1c97fa2/static/sass/styles.scss#L233) and different from a lot of other docs. 

Is there a rule here or a better way to keep them consistent?

**Comment by bartaz** [comment]
It seems that some of that local styling has something to do with their sticky top navigation.

First, I think they are missing `is-sticky` class name on their side navigation component, because from all other local styling it looks like they want it sticky.
The rest of they local styles seems to adjust for the fact that top navigation is sticky as well, so side nav needs to stay below it.

**Comment by bartaz** [comment]
Maybe they implemented it before sticky side-navigation was removed as default and moved to variant: https://vanillaframework.io/docs/patterns/navigation#sticky

**Comment by anthonydillon** [comment]
That was my thinking. So if the guidance is that all docs should follow the docs layout. I'll file an issue to remove/update inconsistencies on the other projects.

@steverydz do you have background on these local styles?

**Comment by steverydz** [comment]
I wasn't involved in the juju.is docs but my guess would be that @bartaz is right, and it was implemented prior to the vanilla pattern.

**Comment by bartaz** [comment]
Reported as a bug in juju.is: https://github.com/canonical-web-and-design/juju.is/issues/363

Closing this one.
