### ISSUE TITLE
Tab strip and tab content components - Figma library

### ISSUE THREAD

**Issue by elioqoshi** [canonical-web-and-design/vanilla-framework#4151]

**Comment by long-chung** [comment]
@elioqoshi looks great and works well.

Just a couple of things:
There is a parameter "is empty" that only has one value. What does this do and do we need it?
I don't see the need for tabs/content? as there are a number of different components that could go in this content area and would be hard to control without making everything a component in order to put it i this placeholder.

**Comment by elioqoshi** [comment]
@long-chung Cool, thanks.

I removed the 'is empty' property, It was a remain from the former component.

You might be right for the tabs/content. I added it as we have it in Vanilla and wanted to mirror it: https://vanillaframework.io/docs/examples/patterns/tabs/content

Though in Figma one would not build it up that way. I will get rid of it then. Will add descriptions and publish then if it's good to go.

**Comment by elioqoshi** [comment]
Published, closing this.
