### ISSUE TITLE
Update p-table--mobile-card to use mobile friendly breakpoint

### ISSUE THREAD

**Issue by petesfrench** [canonical-web-and-design/vanilla-framework#4355]
## Pattern to amend

`p-table--mobile-card`

Currently the breakpoint for this class is set to 1035px but should be set to 485px as it is for mobile view only.

**Comment by clagom** [comment]
WG: we wouldn't recommend changing this default value and behaviour because it depends on the particular use case of the product. We covered this responsive aspects in our modular table spec: https://discourse.ubuntu.com/t/responsive-behaviours/19855 
Can you provide more information on what you would need in this case @petesfrench?

**Comment by petesfrench** [comment]
@clagom It was @davegoddard42 who originally brought it to my attention when we were working on the comparison table on https://microk8s.io/compare. The table responds as expected and is completely readable, but Dave asked if it was possible to have it change to cards at a smaller size. I thought that maybe it was oversight as the name `--mobile-card` implies it only applies to mobile (small) screen. If this is the intended behavior, I can make a custom style for this specific use case.

**Comment by bartaz** [comment]
@petesfrench Yes, this is intended for the tables to turn into cards on medium and small screens (below ~1000px), but I also agree that the name may make it a bit confusing.

As for the page you linked, you seem to be missing some headings in HTML attributes I think, because right now mobile cards make the data incomprehensible. 

<img width="618" alt="Screenshot 2022-03-09 at 14 27 16" src="https://user-images.githubusercontent.com/83575/157451273-af7b37db-face-4e36-8079-7c6bebcfb421.png">

Overall I'm not sure if generic mobile card table is a good pattern here. It would be much more useful in your case for the "cards" to be grouped by column (a product listing its features) instead of each card being a single feature in all 3 products.

**Comment by bartaz** [comment]
@petesfrench In case of customising table mobile card pattern - I believe right now to change the breakpoint it uses you would need to practically copy the whole pattern and use it with different breakpoint. Let us know how challanging it is - maybe we can extract this pattern in a way that will make it easier to configure.

**Comment by davegoddard42** [comment]
@bartaz The first issue @petesfrench was trying to solve was the fact that the data is incomprehensible due to the missing headers. The current breakpoint (1000px) feels way too early on this particular page, which is why we started to explore the breakpoint a bit. 

I actually agree though on this page breaking the rows into cards, as opposed to columns is a better way to handle this data table. I reckon it wouldn't matter so much that it breaks into cards at 1000px because the data would be more readable. 

@petesfrench is it worth us trying that out and seeing what it looks like? It would appear to be a lot less effort than making a custom breakpoint for this page

**Comment by petesfrench** [comment]
@bartaz Thanks for the feedback, If customizing the class is going to be complicated I think it is best to stick with current functionality of vanilla. So let's go with that @davegoddard42

**Comment by petesfrench** [comment]
Closing as we found a work around for the specific use case
