### ISSUE TITLE
Not an issue, just a feedback

### ISSUE THREAD

**Issue by alfuken** [canonical-web-and-design/vanilla-framework#4514]
Being a fan of http://vanilla-js.com, googled "vanilla css".

This project was top result.

Clicked.

Expected the project to be like http://vanilla-js.com.

Expectation not met.

Disappointed.

Not a big deal, just wanted to share.

**Comment by bartaz** [comment]
@alfuken Hey, thanks for stopping by. We are aware of the confusion the name of our framework may create for the ones looking for true "vanilla" experience, but it has quite a history and legacy in our team so we are not at the point where we could change that. But believe us, we tried, because as developers we do understand the meaning "vanilla" has :)

**Comment by anthonydillon** [comment]
Thank you for your feedback. Closing for now. Please comment if you have further comments.
